// Code generated by protoc-gen-go. DO NOT EDIT.
// source: usercenter/t_actiongrowthconfig.proto

package models

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "github.com/golang/protobuf/ptypes/timestamp"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type TActionGrowthConfig struct {
	DayLimit             string   `protobuf:"bytes,1,opt,name=day_limit,json=dayLimit,proto3" json:"day_limit,omitempty"`
	WeekLimit            string   `protobuf:"bytes,2,opt,name=week_limit,json=weekLimit,proto3" json:"week_limit,omitempty"`
	MonthLimit           string   `protobuf:"bytes,3,opt,name=month_limit,json=monthLimit,proto3" json:"month_limit,omitempty"`
	Level1Value          string   `protobuf:"bytes,4,opt,name=level1_value,json=level1Value,proto3" json:"level1_value,omitempty"`
	Level2Value          string   `protobuf:"bytes,5,opt,name=level2_value,json=level2Value,proto3" json:"level2_value,omitempty"`
	Level3Value          string   `protobuf:"bytes,6,opt,name=level3_value,json=level3Value,proto3" json:"level3_value,omitempty"`
	Level4Value          string   `protobuf:"bytes,7,opt,name=level4_value,json=level4Value,proto3" json:"level4_value,omitempty"`
	Level5Value          string   `protobuf:"bytes,8,opt,name=level5_value,json=level5Value,proto3" json:"level5_value,omitempty"`
	Level6Value          string   `protobuf:"bytes,9,opt,name=level6_value,json=level6Value,proto3" json:"level6_value,omitempty"`
	Level7Value          string   `protobuf:"bytes,10,opt,name=level7_value,json=level7Value,proto3" json:"level7_value,omitempty"`
	Descs                string   `protobuf:"bytes,11,opt,name=descs,proto3" json:"descs,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TActionGrowthConfig) Reset()         { *m = TActionGrowthConfig{} }
func (m *TActionGrowthConfig) String() string { return proto.CompactTextString(m) }
func (*TActionGrowthConfig) ProtoMessage()    {}
func (*TActionGrowthConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_t_actiongrowthconfig_5f2092e387febc66, []int{0}
}
func (m *TActionGrowthConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TActionGrowthConfig.Unmarshal(m, b)
}
func (m *TActionGrowthConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TActionGrowthConfig.Marshal(b, m, deterministic)
}
func (dst *TActionGrowthConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TActionGrowthConfig.Merge(dst, src)
}
func (m *TActionGrowthConfig) XXX_Size() int {
	return xxx_messageInfo_TActionGrowthConfig.Size(m)
}
func (m *TActionGrowthConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_TActionGrowthConfig.DiscardUnknown(m)
}

var xxx_messageInfo_TActionGrowthConfig proto.InternalMessageInfo

func (m *TActionGrowthConfig) GetDayLimit() string {
	if m != nil {
		return m.DayLimit
	}
	return ""
}

func (m *TActionGrowthConfig) GetWeekLimit() string {
	if m != nil {
		return m.WeekLimit
	}
	return ""
}

func (m *TActionGrowthConfig) GetMonthLimit() string {
	if m != nil {
		return m.MonthLimit
	}
	return ""
}

func (m *TActionGrowthConfig) GetLevel1Value() string {
	if m != nil {
		return m.Level1Value
	}
	return ""
}

func (m *TActionGrowthConfig) GetLevel2Value() string {
	if m != nil {
		return m.Level2Value
	}
	return ""
}

func (m *TActionGrowthConfig) GetLevel3Value() string {
	if m != nil {
		return m.Level3Value
	}
	return ""
}

func (m *TActionGrowthConfig) GetLevel4Value() string {
	if m != nil {
		return m.Level4Value
	}
	return ""
}

func (m *TActionGrowthConfig) GetLevel5Value() string {
	if m != nil {
		return m.Level5Value
	}
	return ""
}

func (m *TActionGrowthConfig) GetLevel6Value() string {
	if m != nil {
		return m.Level6Value
	}
	return ""
}

func (m *TActionGrowthConfig) GetLevel7Value() string {
	if m != nil {
		return m.Level7Value
	}
	return ""
}

func (m *TActionGrowthConfig) GetDescs() string {
	if m != nil {
		return m.Descs
	}
	return ""
}

func init() {
	proto.RegisterType((*TActionGrowthConfig)(nil), "usercenter.TActionGrowthConfig")
}

func init() {
	proto.RegisterFile("usercenter/t_actiongrowthconfig.proto", fileDescriptor_t_actiongrowthconfig_5f2092e387febc66)
}

var fileDescriptor_t_actiongrowthconfig_5f2092e387febc66 = []byte{
	// 285 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0xd1, 0x3b, 0x4f, 0xc3, 0x30,
	0x14, 0x05, 0x60, 0xb5, 0xd0, 0xd2, 0x38, 0x4c, 0x81, 0x21, 0x02, 0x21, 0x1e, 0x12, 0x12, 0x53,
	0x23, 0x9a, 0x3e, 0x06, 0x26, 0x60, 0x60, 0x61, 0x42, 0x88, 0x81, 0x25, 0x72, 0x92, 0xdb, 0xc4,
	0xc2, 0x8e, 0xa3, 0xf8, 0xa6, 0x55, 0x7e, 0x3c, 0x12, 0x8a, 0x6d, 0x51, 0x67, 0xcb, 0x3d, 0xe7,
	0x53, 0xce, 0x60, 0x72, 0xdf, 0x2a, 0x68, 0x32, 0xa8, 0x10, 0x9a, 0x08, 0x13, 0x9a, 0x21, 0x93,
	0x55, 0xd1, 0xc8, 0x3d, 0x96, 0x99, 0xac, 0xb6, 0xac, 0x98, 0xd7, 0x8d, 0x44, 0x19, 0x90, 0x03,
	0xbb, 0x78, 0x2a, 0x18, 0x96, 0x6d, 0x3a, 0xcf, 0xa4, 0x88, 0x0a, 0xc9, 0x69, 0x55, 0x44, 0x1a,
	0xa5, 0xed, 0x36, 0xaa, 0xb1, 0xab, 0x41, 0x45, 0xc8, 0x04, 0x28, 0xa4, 0xa2, 0x3e, 0x7c, 0x99,
	0x1f, 0xdd, 0xfd, 0x8e, 0xc9, 0xd9, 0xe7, 0xb3, 0x9e, 0x79, 0xd3, 0x33, 0xaf, 0x7a, 0x26, 0xb8,
	0x24, 0x5e, 0x4e, 0xbb, 0x84, 0x33, 0xc1, 0x30, 0x1c, 0xdd, 0x8c, 0x1e, 0xbc, 0x8f, 0x59, 0x4e,
	0xbb, 0xf7, 0xfe, 0x0e, 0xae, 0x08, 0xd9, 0x03, 0xfc, 0xd8, 0x76, 0xac, 0x5b, 0xaf, 0x4f, 0x4c,
	0x7d, 0x4d, 0x7c, 0x21, 0x2b, 0x2c, 0x6d, 0x7f, 0xa4, 0x7b, 0xa2, 0x23, 0x03, 0x6e, 0xc9, 0x29,
	0x87, 0x1d, 0xf0, 0xc7, 0x64, 0x47, 0x79, 0x0b, 0xe1, 0xb1, 0x16, 0xbe, 0xc9, 0xbe, 0xfa, 0xe8,
	0x9f, 0x2c, 0x2c, 0x99, 0x38, 0x64, 0x31, 0x24, 0xb1, 0x25, 0x53, 0x87, 0xc4, 0x43, 0xb2, 0xb4,
	0xe4, 0xc4, 0x21, 0xcb, 0x21, 0x59, 0x59, 0x32, 0x73, 0xc8, 0x6a, 0x48, 0xd6, 0x96, 0x78, 0x0e,
	0x59, 0x0f, 0xc9, 0xc6, 0x12, 0xe2, 0x90, 0x8d, 0x21, 0xe7, 0x64, 0x92, 0x83, 0xca, 0x54, 0xe8,
	0xeb, 0xce, 0x1c, 0x2f, 0xb3, 0xef, 0xa9, 0x90, 0x39, 0x70, 0x95, 0x4e, 0xf5, 0x83, 0xc4, 0x7f,
	0x01, 0x00, 0x00, 0xff, 0xff, 0x89, 0x03, 0x1f, 0x56, 0x02, 0x02, 0x00, 0x00,
}
