// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: usercenter/t_actiongrowthconfig.proto

/*
Package models is a generated protocol buffer package.

It is generated from these files:
	usercenter/t_actiongrowthconfig.proto
	usercenter/t_actionscoreconfigbackups.proto
	usercenter/t_actionscoreconfig.proto
	usercenter/t_actionvitalityconfig.proto
	usercenter/t_awardpool.proto
	usercenter/t_awardtype.proto
	usercenter/t_basefile.proto
	usercenter/t_blacklistdetail.proto
	usercenter/t_blacklist.proto
	usercenter/t_blacklisttemp.proto
	usercenter/t_brand.proto
	usercenter/t_cpbillcycleprocessstatus.proto
	usercenter/t_cpbillcycle.proto
	usercenter/t_exchangegoodslimit.proto
	usercenter/t_exchangegoods.proto
	usercenter/t_floworderds.proto
	usercenter/t_getmcoinlist.proto
	usercenter/t_goldconfig.proto
	usercenter/t_gradehistory.proto
	usercenter/t_gradetitle.proto
	usercenter/t_ipauthentication.proto
	usercenter/t_ipfilter.proto
	usercenter/t_iplist.proto
	usercenter/t_ipsource.proto
	usercenter/t_iptype.proto
	usercenter/t_lable.proto
	usercenter/t_mcoindetail.proto
	usercenter/t_mcoinexchange.proto
	usercenter/t_mcoinexrate.proto
	usercenter/t_mcoinusedetail.proto
	usercenter/t_mcouponsinfohis.proto
	usercenter/t_mcouponsinfo.proto
	usercenter/t_medalconfig.proto
	usercenter/t_memberactionlimit.proto
	usercenter/t_memberdegradetemp.proto
	usercenter/t_membergrade.proto
	usercenter/t_membermcoinreset.proto
	usercenter/t_member.proto
	usercenter/t_memberscoredetail.proto
	usercenter/t_memberscorereset.proto
	usercenter/t_membersignconfig.proto
	usercenter/t_membertaskmobile.proto
	usercenter/t_membertask.proto
	usercenter/t_memberunsignactionlimit.proto
	usercenter/t_memberunsignconfig.proto
	usercenter/t_memberupgraderecord.proto
	usercenter/t_membervitalitydetail.proto
	usercenter/t_membervitalityexpiretemp.proto
	usercenter/t_messagetype.proto
	usercenter/t_mmcurrencyhisttable.proto
	usercenter/t_mmcurrencytable.proto
	usercenter/t_mmpayorder.proto
	usercenter/t_mmtag.proto
	usercenter/t_mmtagtype.proto
	usercenter/t_mmzerosubscribe.proto
	usercenter/t_mmzerounsubscribehistory.proto
	usercenter/t_mmzerounsubscribe.proto
	usercenter/t_oaabichecksum.proto
	usercenter/t_operatelog.proto
	usercenter/t_rechargebatch.proto
	usercenter/t_rightspackageorder.proto
	usercenter/t_rulelablemapping.proto
	usercenter/t_scoreexchange.proto
	usercenter/t_screeningmodel.proto
	usercenter/t_screeningresult.proto
	usercenter/t_screeningrule.proto
	usercenter/t_servicenode.proto
	usercenter/t_smsnotify.proto
	usercenter/t_srvsupporttagname.proto
	usercenter/t_subsfetion.proto
	usercenter/t_syncrecord.proto
	usercenter/t_taskexcute.proto
	usercenter/t_task.proto
	usercenter/t_taskstrategy.proto
	usercenter/t_tesst01.proto
	usercenter/t_tqborderinfohist.proto
	usercenter/t_tqborderinfo.proto
	usercenter/t_updmmclientusers.proto
	usercenter/t_usemcoinlist.proto
	usercenter/t_usergrade.proto
	usercenter/t_userinfo.proto
	usercenter/t_userportrait.proto
	usercenter/t_userportraittemp.proto
	usercenter/t_usersubsstatus.proto

It has these top-level messages:
	TActionGrowthConfig
	TActionScoreConfigBackups
	TActionScoreConfig
	TActionVitalityConfig
	TAwardPool
	TAwardType
	TBasefile
	TBlacklistDetail
	TBlackList
	TBlackListTemp
	TBrand
	TCpBillCycleProcessStatus
	TCpBillCycle
	TExchangeGoodsLimit
	TExchangeGoods
	TFlowOrderDs
	TGetmcoinlist
	TGoldConfig
	TGradehistory
	TGradeTitle
	TIpAuthentication
	TIpFilter
	TIpList
	TIpSource
	TIpType
	TLable
	TMcoinDetail
	TMcoinExchange
	TMcoinExrate
	TMcoinusedetail
	TMcouponsinfoHis
	TMcouponsinfo
	TMedalConfig
	TMemberActionLimit
	TMemberDegradeTemp
	TMemberGrade
	TMemberMcoinReset
	TMember
	TMemberScoreDetail
	TMemberScoreReset
	TMemberSignConfig
	TMemberTaskMobile
	TMemberTask
	TMemberUnsignActionLimit
	TMemberUnsignConfig
	TMemberUpgradeRecord
	TMemberVitalityDetail
	TMemberVitalityExpireTemp
	TMessageType
	TMmcurrencyHistTable
	TMmcurrencyTable
	TMmPayOrder
	TMmTag
	TMmTagType
	TMmZeroSubscribe
	TMmZeroUnsubscribeHistory
	TMmZeroUnsubscribe
	TOaAbiChecksum
	TOperateLog
	TRechargeBatch
	TRightsPackageOrder
	TRuleLableMapping
	TScoreExchange
	TScreeningModel
	TScreeningResult
	TScreeningRule
	TServiceNode
	TSmsnotify
	TSrvSupportTagName
	TSubsFetion
	TSyncRecord
	TTaskExcute
	TTask
	TTaskStrategy
	TTesst01
	TTqbOrderinfoHist
	TTqbOrderinfo
	TUpdMmclientUsers
	TUsemcoinlist
	TUserGrade
	TUserInfo
	TUserPortrait
	TUserPortraitTemp
	TUsersubsStatus
*/
package models

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "github.com/golang/protobuf/ptypes/timestamp"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package
