// Code generated by protoc-gen-go. DO NOT EDIT.
// source: usercenter/t_actionscoreconfigbackups.proto

package models

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import timestamp "github.com/golang/protobuf/ptypes/timestamp"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type TActionScoreConfigBackups struct {
	Id                   string               `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string               `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	ActionCode           string               `protobuf:"bytes,3,opt,name=action_code,json=actionCode,proto3" json:"action_code,omitempty"`
	Type                 string               `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`
	Source               string               `protobuf:"bytes,5,opt,name=source,proto3" json:"source,omitempty"`
	Cycle                string               `protobuf:"bytes,6,opt,name=cycle,proto3" json:"cycle,omitempty"`
	Status               string               `protobuf:"bytes,7,opt,name=status,proto3" json:"status,omitempty"`
	Remark               string               `protobuf:"bytes,8,opt,name=remark,proto3" json:"remark,omitempty"`
	CreateDate           *timestamp.Timestamp `protobuf:"bytes,9,opt,name=create_date,json=createDate,proto3" json:"create_date,omitempty"`
	CreateUser           string               `protobuf:"bytes,10,opt,name=create_user,json=createUser,proto3" json:"create_user,omitempty"`
	Lupddate             *timestamp.Timestamp `protobuf:"bytes,11,opt,name=lupddate,proto3" json:"lupddate,omitempty"`
	LogoUrl              string               `protobuf:"bytes,12,opt,name=logo_url,json=logoUrl,proto3" json:"logo_url,omitempty"`
	DayLimit             string               `protobuf:"bytes,13,opt,name=day_limit,json=dayLimit,proto3" json:"day_limit,omitempty"`
	WeekLimit            string               `protobuf:"bytes,14,opt,name=week_limit,json=weekLimit,proto3" json:"week_limit,omitempty"`
	MonthLimit           string               `protobuf:"bytes,15,opt,name=month_limit,json=monthLimit,proto3" json:"month_limit,omitempty"`
	LimitCount           string               `protobuf:"bytes,16,opt,name=limit_count,json=limitCount,proto3" json:"limit_count,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *TActionScoreConfigBackups) Reset()         { *m = TActionScoreConfigBackups{} }
func (m *TActionScoreConfigBackups) String() string { return proto.CompactTextString(m) }
func (*TActionScoreConfigBackups) ProtoMessage()    {}
func (*TActionScoreConfigBackups) Descriptor() ([]byte, []int) {
	return fileDescriptor_t_actionscoreconfigbackups_9fad63bf4c2f920c, []int{0}
}
func (m *TActionScoreConfigBackups) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TActionScoreConfigBackups.Unmarshal(m, b)
}
func (m *TActionScoreConfigBackups) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TActionScoreConfigBackups.Marshal(b, m, deterministic)
}
func (dst *TActionScoreConfigBackups) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TActionScoreConfigBackups.Merge(dst, src)
}
func (m *TActionScoreConfigBackups) XXX_Size() int {
	return xxx_messageInfo_TActionScoreConfigBackups.Size(m)
}
func (m *TActionScoreConfigBackups) XXX_DiscardUnknown() {
	xxx_messageInfo_TActionScoreConfigBackups.DiscardUnknown(m)
}

var xxx_messageInfo_TActionScoreConfigBackups proto.InternalMessageInfo

func (m *TActionScoreConfigBackups) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *TActionScoreConfigBackups) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *TActionScoreConfigBackups) GetActionCode() string {
	if m != nil {
		return m.ActionCode
	}
	return ""
}

func (m *TActionScoreConfigBackups) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *TActionScoreConfigBackups) GetSource() string {
	if m != nil {
		return m.Source
	}
	return ""
}

func (m *TActionScoreConfigBackups) GetCycle() string {
	if m != nil {
		return m.Cycle
	}
	return ""
}

func (m *TActionScoreConfigBackups) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *TActionScoreConfigBackups) GetRemark() string {
	if m != nil {
		return m.Remark
	}
	return ""
}

func (m *TActionScoreConfigBackups) GetCreateDate() *timestamp.Timestamp {
	if m != nil {
		return m.CreateDate
	}
	return nil
}

func (m *TActionScoreConfigBackups) GetCreateUser() string {
	if m != nil {
		return m.CreateUser
	}
	return ""
}

func (m *TActionScoreConfigBackups) GetLupddate() *timestamp.Timestamp {
	if m != nil {
		return m.Lupddate
	}
	return nil
}

func (m *TActionScoreConfigBackups) GetLogoUrl() string {
	if m != nil {
		return m.LogoUrl
	}
	return ""
}

func (m *TActionScoreConfigBackups) GetDayLimit() string {
	if m != nil {
		return m.DayLimit
	}
	return ""
}

func (m *TActionScoreConfigBackups) GetWeekLimit() string {
	if m != nil {
		return m.WeekLimit
	}
	return ""
}

func (m *TActionScoreConfigBackups) GetMonthLimit() string {
	if m != nil {
		return m.MonthLimit
	}
	return ""
}

func (m *TActionScoreConfigBackups) GetLimitCount() string {
	if m != nil {
		return m.LimitCount
	}
	return ""
}

func init() {
	proto.RegisterType((*TActionScoreConfigBackups)(nil), "usercenter.TActionScoreConfigBackups")
}

func init() {
	proto.RegisterFile("usercenter/t_actionscoreconfigbackups.proto", fileDescriptor_t_actionscoreconfigbackups_9fad63bf4c2f920c)
}

var fileDescriptor_t_actionscoreconfigbackups_9fad63bf4c2f920c = []byte{
	// 392 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x90, 0xcd, 0x6b, 0x14, 0x41,
	0x10, 0xc5, 0xd9, 0x75, 0xb3, 0x99, 0xad, 0xd1, 0x28, 0x8d, 0x48, 0x27, 0x22, 0x09, 0x9e, 0x02,
	0xc2, 0x0c, 0x28, 0x78, 0xc9, 0xc9, 0xac, 0x47, 0x4f, 0x31, 0xb9, 0x78, 0x19, 0x7a, 0xbb, 0x2b,
	0x93, 0x61, 0xbb, 0xa7, 0x86, 0xfe, 0x40, 0xf6, 0xe8, 0x7f, 0x2e, 0x5d, 0x3d, 0x49, 0x8e, 0xb9,
	0xf5, 0xfb, 0xbd, 0xd7, 0xf5, 0x05, 0x5f, 0x52, 0x40, 0xaf, 0x71, 0x8c, 0xe8, 0xdb, 0xd8, 0x29,
	0x1d, 0x07, 0x1a, 0x83, 0x26, 0x8f, 0x9a, 0xc6, 0xfb, 0xa1, 0xdf, 0x29, 0xbd, 0x4f, 0x53, 0x68,
	0x26, 0x4f, 0x91, 0x04, 0x3c, 0x87, 0xcf, 0xae, 0xfa, 0x21, 0x3e, 0xa4, 0x5d, 0xa3, 0xc9, 0xb5,
	0x3d, 0x59, 0x35, 0xf6, 0x2d, 0x87, 0x76, 0xe9, 0xbe, 0x9d, 0xe2, 0x61, 0xc2, 0xd0, 0xc6, 0xc1,
	0x61, 0x88, 0xca, 0x4d, 0xcf, 0xaf, 0x52, 0xe8, 0xf3, 0xbf, 0x15, 0x9c, 0xde, 0xfe, 0xe0, 0x66,
	0xbf, 0x73, 0xb3, 0x2d, 0x37, 0xbb, 0x2e, 0xcd, 0xc4, 0x09, 0x2c, 0x07, 0x23, 0x17, 0x17, 0x8b,
	0xcb, 0xcd, 0xcd, 0x72, 0x30, 0x42, 0xc0, 0x6a, 0x54, 0x0e, 0xe5, 0x92, 0x09, 0xbf, 0xc5, 0x39,
	0xd4, 0x65, 0xd8, 0x4e, 0x93, 0x41, 0xf9, 0x8a, 0x2d, 0x28, 0x68, 0x4b, 0x06, 0xf3, 0xa7, 0x3c,
	0x85, 0x5c, 0x95, 0x4f, 0xf9, 0x2d, 0x3e, 0xc0, 0x3a, 0x50, 0xf2, 0x1a, 0xe5, 0x11, 0xd3, 0x59,
	0x89, 0xf7, 0x70, 0xa4, 0x0f, 0xda, 0xa2, 0x5c, 0x33, 0x2e, 0x82, 0xd3, 0x51, 0xc5, 0x14, 0xe4,
	0xf1, 0x9c, 0x66, 0x95, 0xb9, 0x47, 0xa7, 0xfc, 0x5e, 0x56, 0x85, 0x17, 0x25, 0xae, 0xa0, 0xd6,
	0x1e, 0x55, 0xc4, 0xce, 0xa8, 0x88, 0x72, 0x73, 0xb1, 0xb8, 0xac, 0xbf, 0x9e, 0x35, 0x3d, 0x51,
	0x6f, 0xb1, 0x79, 0x3c, 0x4e, 0x73, 0xfb, 0x78, 0x8b, 0x1b, 0x28, 0xf1, 0x9f, 0x2a, 0xf2, 0x3e,
	0xf3, 0xe7, 0x7c, 0x63, 0x09, 0x65, 0x9f, 0x82, 0xee, 0x02, 0x7a, 0xf1, 0x1d, 0x2a, 0x9b, 0x26,
	0xc3, 0xa5, 0xeb, 0x17, 0x4b, 0x3f, 0x65, 0xc5, 0x29, 0x54, 0x96, 0x7a, 0xea, 0x92, 0xb7, 0xf2,
	0x35, 0x57, 0x3d, 0xce, 0xfa, 0xce, 0x5b, 0xf1, 0x11, 0x36, 0x46, 0x1d, 0x3a, 0x3b, 0xb8, 0x21,
	0xca, 0x37, 0xec, 0x55, 0x46, 0x1d, 0x7e, 0x65, 0x2d, 0x3e, 0x01, 0xfc, 0x45, 0xdc, 0xcf, 0xee,
	0x09, 0xbb, 0x9b, 0x4c, 0x8a, 0x7d, 0x0e, 0xb5, 0xa3, 0x31, 0x3e, 0xcc, 0xfe, 0xdb, 0x32, 0x2f,
	0xa3, 0xa7, 0x00, 0x5b, 0x9d, 0xa6, 0x34, 0x46, 0xf9, 0xae, 0x04, 0x18, 0x6d, 0x33, 0xb9, 0xae,
	0xfe, 0xac, 0x1d, 0x19, 0xb4, 0x61, 0xb7, 0xe6, 0x05, 0xbe, 0xfd, 0x0f, 0x00, 0x00, 0xff, 0xff,
	0x0d, 0x82, 0x6b, 0xcf, 0x8c, 0x02, 0x00, 0x00,
}
