// Code generated by protoc-gen-go. DO NOT EDIT.
// source: usercenter/t_actionvitalityconfig.proto

package models

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "github.com/golang/protobuf/ptypes/timestamp"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type TActionVitalityConfig struct {
	ActionScoreId        string   `protobuf:"bytes,1,opt,name=action_score_id,json=actionScoreId,proto3" json:"action_score_id,omitempty"`
	PtMemberScore        string   `protobuf:"bytes,2,opt,name=pt_member_score,json=ptMemberScore,proto3" json:"pt_member_score,omitempty"`
	QtMemberScore        string   `protobuf:"bytes,3,opt,name=qt_member_score,json=qtMemberScore,proto3" json:"qt_member_score,omitempty"`
	ByMemberScore        string   `protobuf:"bytes,4,opt,name=by_member_score,json=byMemberScore,proto3" json:"by_member_score,omitempty"`
	HjMemberScore        string   `protobuf:"bytes,5,opt,name=hj_member_score,json=hjMemberScore,proto3" json:"hj_member_score,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TActionVitalityConfig) Reset()         { *m = TActionVitalityConfig{} }
func (m *TActionVitalityConfig) String() string { return proto.CompactTextString(m) }
func (*TActionVitalityConfig) ProtoMessage()    {}
func (*TActionVitalityConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_t_actionvitalityconfig_119ca3c2ff07671e, []int{0}
}
func (m *TActionVitalityConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TActionVitalityConfig.Unmarshal(m, b)
}
func (m *TActionVitalityConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TActionVitalityConfig.Marshal(b, m, deterministic)
}
func (dst *TActionVitalityConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TActionVitalityConfig.Merge(dst, src)
}
func (m *TActionVitalityConfig) XXX_Size() int {
	return xxx_messageInfo_TActionVitalityConfig.Size(m)
}
func (m *TActionVitalityConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_TActionVitalityConfig.DiscardUnknown(m)
}

var xxx_messageInfo_TActionVitalityConfig proto.InternalMessageInfo

func (m *TActionVitalityConfig) GetActionScoreId() string {
	if m != nil {
		return m.ActionScoreId
	}
	return ""
}

func (m *TActionVitalityConfig) GetPtMemberScore() string {
	if m != nil {
		return m.PtMemberScore
	}
	return ""
}

func (m *TActionVitalityConfig) GetQtMemberScore() string {
	if m != nil {
		return m.QtMemberScore
	}
	return ""
}

func (m *TActionVitalityConfig) GetByMemberScore() string {
	if m != nil {
		return m.ByMemberScore
	}
	return ""
}

func (m *TActionVitalityConfig) GetHjMemberScore() string {
	if m != nil {
		return m.HjMemberScore
	}
	return ""
}

func init() {
	proto.RegisterType((*TActionVitalityConfig)(nil), "usercenter.TActionVitalityConfig")
}

func init() {
	proto.RegisterFile("usercenter/t_actionvitalityconfig.proto", fileDescriptor_t_actionvitalityconfig_119ca3c2ff07671e)
}

var fileDescriptor_t_actionvitalityconfig_119ca3c2ff07671e = []byte{
	// 228 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0xcf, 0xbf, 0x4a, 0x04, 0x31,
	0x10, 0x06, 0x70, 0xd6, 0x3f, 0x87, 0x2e, 0x88, 0x70, 0x20, 0x1c, 0x56, 0x62, 0xa1, 0x56, 0x97,
	0xc2, 0xd2, 0x4a, 0xad, 0x2c, 0x6c, 0x54, 0x2c, 0x6c, 0x96, 0x24, 0x3b, 0x97, 0xcd, 0xb1, 0xc9,
	0xe4, 0x92, 0x59, 0x21, 0x4f, 0xeb, 0xab, 0xc8, 0x66, 0x84, 0x73, 0xb7, 0x1b, 0x3e, 0x7e, 0xcc,
	0x37, 0x53, 0xdf, 0x0e, 0x09, 0xa2, 0x06, 0x4f, 0x10, 0x05, 0x35, 0x52, 0x93, 0x45, 0xff, 0x6d,
	0x49, 0xf6, 0x96, 0xb2, 0x46, 0xbf, 0xb1, 0x66, 0x1d, 0x22, 0x12, 0x2e, 0xeb, 0x3d, 0xbc, 0x7c,
	0x30, 0x96, 0xba, 0x41, 0xad, 0x35, 0x3a, 0x61, 0xb0, 0x97, 0xde, 0x88, 0x82, 0xd4, 0xb0, 0x11,
	0x81, 0x72, 0x80, 0x24, 0xc8, 0x3a, 0x48, 0x24, 0x5d, 0xd8, 0x4f, 0xbc, 0xe8, 0xfa, 0xa7, 0xaa,
	0x2f, 0x3e, 0x1e, 0x4b, 0xd1, 0xe7, 0x5f, 0xd1, 0x73, 0x29, 0x5a, 0xde, 0xd4, 0xe7, 0x7c, 0x40,
	0x93, 0x34, 0x46, 0x68, 0x6c, 0xbb, 0xaa, 0xae, 0xaa, 0xbb, 0xd3, 0xb7, 0x33, 0x8e, 0xdf, 0xc7,
	0xf4, 0xa5, 0x1d, 0x5d, 0xa0, 0xc6, 0x81, 0x53, 0x10, 0x99, 0xae, 0x0e, 0xd8, 0x05, 0x7a, 0x2d,
	0x69, 0x91, 0xa3, 0xdb, 0xcd, 0xdc, 0x21, 0xbb, 0xdd, 0xdc, 0xa9, 0x3c, 0x75, 0x47, 0xec, 0x54,
	0x9e, 0xb9, 0x6e, 0x3b, 0x75, 0xc7, 0xec, 0xba, 0xed, 0x3f, 0xf7, 0x74, 0xf2, 0xb5, 0x70, 0xd8,
	0x42, 0x9f, 0xd4, 0xa2, 0xbc, 0x7c, 0xff, 0x1b, 0x00, 0x00, 0xff, 0xff, 0x56, 0xdd, 0xdd, 0x29,
	0x66, 0x01, 0x00, 0x00,
}
