// Code generated by protoc-gen-go. DO NOT EDIT.
// source: usercenter/t_blacklistdetail.proto

package models

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import timestamp "github.com/golang/protobuf/ptypes/timestamp"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type TBlacklistDetail struct {
	Id                   string               `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Mobile               string               `protobuf:"bytes,2,opt,name=mobile,proto3" json:"mobile,omitempty"`
	Action               string               `protobuf:"bytes,3,opt,name=action,proto3" json:"action,omitempty"`
	CreateDate           *timestamp.Timestamp `protobuf:"bytes,4,opt,name=create_date,json=createDate,proto3" json:"create_date,omitempty"`
	CreateUser           string               `protobuf:"bytes,5,opt,name=create_user,json=createUser,proto3" json:"create_user,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *TBlacklistDetail) Reset()         { *m = TBlacklistDetail{} }
func (m *TBlacklistDetail) String() string { return proto.CompactTextString(m) }
func (*TBlacklistDetail) ProtoMessage()    {}
func (*TBlacklistDetail) Descriptor() ([]byte, []int) {
	return fileDescriptor_t_blacklistdetail_20b3077eef1c9f84, []int{0}
}
func (m *TBlacklistDetail) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TBlacklistDetail.Unmarshal(m, b)
}
func (m *TBlacklistDetail) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TBlacklistDetail.Marshal(b, m, deterministic)
}
func (dst *TBlacklistDetail) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TBlacklistDetail.Merge(dst, src)
}
func (m *TBlacklistDetail) XXX_Size() int {
	return xxx_messageInfo_TBlacklistDetail.Size(m)
}
func (m *TBlacklistDetail) XXX_DiscardUnknown() {
	xxx_messageInfo_TBlacklistDetail.DiscardUnknown(m)
}

var xxx_messageInfo_TBlacklistDetail proto.InternalMessageInfo

func (m *TBlacklistDetail) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *TBlacklistDetail) GetMobile() string {
	if m != nil {
		return m.Mobile
	}
	return ""
}

func (m *TBlacklistDetail) GetAction() string {
	if m != nil {
		return m.Action
	}
	return ""
}

func (m *TBlacklistDetail) GetCreateDate() *timestamp.Timestamp {
	if m != nil {
		return m.CreateDate
	}
	return nil
}

func (m *TBlacklistDetail) GetCreateUser() string {
	if m != nil {
		return m.CreateUser
	}
	return ""
}

func init() {
	proto.RegisterType((*TBlacklistDetail)(nil), "usercenter.TBlacklistDetail")
}

func init() {
	proto.RegisterFile("usercenter/t_blacklistdetail.proto", fileDescriptor_t_blacklistdetail_20b3077eef1c9f84)
}

var fileDescriptor_t_blacklistdetail_20b3077eef1c9f84 = []byte{
	// 232 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x44, 0x8f, 0xbd, 0x4e, 0x03, 0x31,
	0x10, 0x84, 0x75, 0x07, 0x9c, 0xc0, 0x91, 0x10, 0x72, 0x81, 0xac, 0x34, 0x44, 0xa9, 0x52, 0xd9,
	0x12, 0x94, 0xe9, 0xa2, 0x3c, 0x41, 0x14, 0x1a, 0x9a, 0xc8, 0x3f, 0x8b, 0xb1, 0xb0, 0x6f, 0x4f,
	0xf6, 0x5e, 0xc1, 0x5b, 0xf1, 0x88, 0x28, 0xbe, 0x1c, 0xe9, 0x3c, 0xa3, 0xcf, 0x33, 0xb3, 0x6c,
	0x3d, 0x16, 0xc8, 0x16, 0x7a, 0x82, 0xac, 0xe8, 0x64, 0xa2, 0xb6, 0xdf, 0x31, 0x14, 0x72, 0x40,
	0x3a, 0x44, 0x39, 0x64, 0x24, 0xe4, 0xec, 0xca, 0x2c, 0xb7, 0x3e, 0xd0, 0xd7, 0x68, 0xa4, 0xc5,
	0xa4, 0x3c, 0x46, 0xdd, 0x7b, 0x55, 0x21, 0x33, 0x7e, 0xaa, 0x81, 0x7e, 0x06, 0x28, 0x8a, 0x42,
	0x82, 0x42, 0x3a, 0x0d, 0xd7, 0xd7, 0x14, 0xb4, 0xfe, 0x6d, 0xd8, 0xd3, 0x71, 0x37, 0x77, 0xec,
	0x6b, 0x07, 0x7f, 0x64, 0x6d, 0x70, 0xa2, 0x59, 0x35, 0x9b, 0x87, 0x43, 0x1b, 0x1c, 0x7f, 0x66,
	0x5d, 0x42, 0x13, 0x22, 0x88, 0xb6, 0x7a, 0x17, 0x75, 0xf6, 0xb5, 0xa5, 0x80, 0xbd, 0xb8, 0x99,
	0xfc, 0x49, 0xf1, 0x2d, 0x5b, 0xd8, 0x0c, 0x9a, 0xe0, 0xe4, 0x34, 0x81, 0xb8, 0x5d, 0x35, 0x9b,
	0xc5, 0xeb, 0x52, 0x7a, 0x44, 0x1f, 0x41, 0xce, 0xe3, 0xe4, 0x71, 0xde, 0x72, 0x60, 0x13, 0xbe,
	0xd7, 0x04, 0xfc, 0xe5, 0xff, 0xf3, 0xf9, 0x46, 0x71, 0x57, 0x93, 0x2f, 0xc0, 0x7b, 0x81, 0xbc,
	0xbb, 0xff, 0xe8, 0x12, 0x3a, 0x88, 0xc5, 0x74, 0x35, 0xea, 0xed, 0x2f, 0x00, 0x00, 0xff, 0xff,
	0x9a, 0x10, 0x43, 0x88, 0x32, 0x01, 0x00, 0x00,
}
