// Code generated by protoc-gen-go. DO NOT EDIT.
// source: usercenter/t_ipfilter.proto

package models

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import timestamp "github.com/golang/protobuf/ptypes/timestamp"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type TIpFilter struct {
	Id                   string               `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Ip                   string               `protobuf:"bytes,2,opt,name=ip,proto3" json:"ip,omitempty"`
	Type                 string               `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	Createdate           *timestamp.Timestamp `protobuf:"bytes,4,opt,name=createdate,proto3" json:"createdate,omitempty"`
	Lupddate             *timestamp.Timestamp `protobuf:"bytes,5,opt,name=lupddate,proto3" json:"lupddate,omitempty"`
	Descs                string               `protobuf:"bytes,6,opt,name=descs,proto3" json:"descs,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *TIpFilter) Reset()         { *m = TIpFilter{} }
func (m *TIpFilter) String() string { return proto.CompactTextString(m) }
func (*TIpFilter) ProtoMessage()    {}
func (*TIpFilter) Descriptor() ([]byte, []int) {
	return fileDescriptor_t_ipfilter_66a2288dce44527f, []int{0}
}
func (m *TIpFilter) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TIpFilter.Unmarshal(m, b)
}
func (m *TIpFilter) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TIpFilter.Marshal(b, m, deterministic)
}
func (dst *TIpFilter) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TIpFilter.Merge(dst, src)
}
func (m *TIpFilter) XXX_Size() int {
	return xxx_messageInfo_TIpFilter.Size(m)
}
func (m *TIpFilter) XXX_DiscardUnknown() {
	xxx_messageInfo_TIpFilter.DiscardUnknown(m)
}

var xxx_messageInfo_TIpFilter proto.InternalMessageInfo

func (m *TIpFilter) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *TIpFilter) GetIp() string {
	if m != nil {
		return m.Ip
	}
	return ""
}

func (m *TIpFilter) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *TIpFilter) GetCreatedate() *timestamp.Timestamp {
	if m != nil {
		return m.Createdate
	}
	return nil
}

func (m *TIpFilter) GetLupddate() *timestamp.Timestamp {
	if m != nil {
		return m.Lupddate
	}
	return nil
}

func (m *TIpFilter) GetDescs() string {
	if m != nil {
		return m.Descs
	}
	return ""
}

func init() {
	proto.RegisterType((*TIpFilter)(nil), "usercenter.TIpFilter")
}

func init() {
	proto.RegisterFile("usercenter/t_ipfilter.proto", fileDescriptor_t_ipfilter_66a2288dce44527f)
}

var fileDescriptor_t_ipfilter_66a2288dce44527f = []byte{
	// 229 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x8e, 0x31, 0x4f, 0xc3, 0x30,
	0x10, 0x85, 0x95, 0xd0, 0x46, 0xed, 0x21, 0x31, 0x58, 0x0c, 0x56, 0x59, 0x2a, 0xa6, 0x4e, 0xb6,
	0x04, 0x12, 0x03, 0x6c, 0x0c, 0x48, 0xac, 0x55, 0x27, 0x16, 0x94, 0xc4, 0x57, 0x63, 0xc9, 0xa9,
	0x4f, 0xf6, 0x65, 0xe0, 0x27, 0xf2, 0xaf, 0x10, 0x57, 0x4a, 0xd8, 0xba, 0xbd, 0x67, 0xbf, 0xf7,
	0xdd, 0x83, 0x9b, 0xb1, 0x60, 0xee, 0xf1, 0xc0, 0x98, 0x2d, 0xbf, 0x07, 0xda, 0x87, 0xc8, 0x98,
	0x0d, 0xe5, 0xc4, 0x49, 0xc1, 0xf4, 0xb9, 0x7a, 0xf2, 0x81, 0x3f, 0xc6, 0xce, 0xf4, 0x69, 0xb0,
	0x3e, 0xc5, 0xf6, 0xe0, 0xad, 0x84, 0xba, 0x71, 0x6f, 0x89, 0x3f, 0x09, 0x8b, 0xe5, 0x30, 0x60,
	0xe1, 0x76, 0xa0, 0x49, 0x1d, 0x41, 0xb7, 0x5f, 0x15, 0x2c, 0x77, 0xaf, 0xf4, 0x22, 0x70, 0x75,
	0x05, 0x75, 0x70, 0xba, 0x5a, 0x57, 0x9b, 0xe5, 0xb6, 0x0e, 0x4e, 0x3c, 0xe9, 0xfa, 0xd7, 0x93,
	0x52, 0x30, 0xfb, 0x01, 0xea, 0x0b, 0x79, 0x11, 0xad, 0x1e, 0x01, 0xfa, 0x8c, 0x2d, 0xa3, 0x6b,
	0x19, 0xf5, 0x6c, 0x5d, 0x6d, 0x2e, 0xef, 0x56, 0xc6, 0xa7, 0xe4, 0x23, 0x9a, 0xd3, 0x10, 0xb3,
	0x3b, 0xdd, 0xdd, 0xfe, 0x4b, 0xab, 0x07, 0x58, 0xc4, 0x91, 0x9c, 0x34, 0xe7, 0x67, 0x9b, 0x7f,
	0x59, 0x75, 0x0d, 0x73, 0x87, 0xa5, 0x2f, 0xba, 0x91, 0x21, 0x47, 0xf3, 0xbc, 0x78, 0x6b, 0x86,
	0xe4, 0x30, 0x96, 0xae, 0x91, 0xf6, 0xfd, 0x77, 0x00, 0x00, 0x00, 0xff, 0xff, 0x6f, 0x32, 0x97,
	0xe8, 0x44, 0x01, 0x00, 0x00,
}
