// Code generated by protoc-gen-go. DO NOT EDIT.
// source: usercenter/t_mcoinexrate.proto

package models

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import timestamp "github.com/golang/protobuf/ptypes/timestamp"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type TMcoinExrate struct {
	Id                   string               `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	MemberGrade          string               `protobuf:"bytes,2,opt,name=member_grade,json=memberGrade,proto3" json:"member_grade,omitempty"`
	ScoreNum             string               `protobuf:"bytes,3,opt,name=score_num,json=scoreNum,proto3" json:"score_num,omitempty"`
	McoinNum             string               `protobuf:"bytes,4,opt,name=mcoin_num,json=mcoinNum,proto3" json:"mcoin_num,omitempty"`
	DayLimit             string               `protobuf:"bytes,5,opt,name=day_limit,json=dayLimit,proto3" json:"day_limit,omitempty"`
	PersonLimit          string               `protobuf:"bytes,6,opt,name=person_limit,json=personLimit,proto3" json:"person_limit,omitempty"`
	CurrentMcoinNum      string               `protobuf:"bytes,7,opt,name=current_mcoin_num,json=currentMcoinNum,proto3" json:"current_mcoin_num,omitempty"`
	ExchangedMcoinNum    string               `protobuf:"bytes,8,opt,name=exchanged_mcoin_num,json=exchangedMcoinNum,proto3" json:"exchanged_mcoin_num,omitempty"`
	CreateDate           *timestamp.Timestamp `protobuf:"bytes,9,opt,name=create_date,json=createDate,proto3" json:"create_date,omitempty"`
	CreateUser           string               `protobuf:"bytes,10,opt,name=create_user,json=createUser,proto3" json:"create_user,omitempty"`
	Lupddate             *timestamp.Timestamp `protobuf:"bytes,11,opt,name=lupddate,proto3" json:"lupddate,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *TMcoinExrate) Reset()         { *m = TMcoinExrate{} }
func (m *TMcoinExrate) String() string { return proto.CompactTextString(m) }
func (*TMcoinExrate) ProtoMessage()    {}
func (*TMcoinExrate) Descriptor() ([]byte, []int) {
	return fileDescriptor_t_mcoinexrate_584c554a65e27887, []int{0}
}
func (m *TMcoinExrate) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TMcoinExrate.Unmarshal(m, b)
}
func (m *TMcoinExrate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TMcoinExrate.Marshal(b, m, deterministic)
}
func (dst *TMcoinExrate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TMcoinExrate.Merge(dst, src)
}
func (m *TMcoinExrate) XXX_Size() int {
	return xxx_messageInfo_TMcoinExrate.Size(m)
}
func (m *TMcoinExrate) XXX_DiscardUnknown() {
	xxx_messageInfo_TMcoinExrate.DiscardUnknown(m)
}

var xxx_messageInfo_TMcoinExrate proto.InternalMessageInfo

func (m *TMcoinExrate) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *TMcoinExrate) GetMemberGrade() string {
	if m != nil {
		return m.MemberGrade
	}
	return ""
}

func (m *TMcoinExrate) GetScoreNum() string {
	if m != nil {
		return m.ScoreNum
	}
	return ""
}

func (m *TMcoinExrate) GetMcoinNum() string {
	if m != nil {
		return m.McoinNum
	}
	return ""
}

func (m *TMcoinExrate) GetDayLimit() string {
	if m != nil {
		return m.DayLimit
	}
	return ""
}

func (m *TMcoinExrate) GetPersonLimit() string {
	if m != nil {
		return m.PersonLimit
	}
	return ""
}

func (m *TMcoinExrate) GetCurrentMcoinNum() string {
	if m != nil {
		return m.CurrentMcoinNum
	}
	return ""
}

func (m *TMcoinExrate) GetExchangedMcoinNum() string {
	if m != nil {
		return m.ExchangedMcoinNum
	}
	return ""
}

func (m *TMcoinExrate) GetCreateDate() *timestamp.Timestamp {
	if m != nil {
		return m.CreateDate
	}
	return nil
}

func (m *TMcoinExrate) GetCreateUser() string {
	if m != nil {
		return m.CreateUser
	}
	return ""
}

func (m *TMcoinExrate) GetLupddate() *timestamp.Timestamp {
	if m != nil {
		return m.Lupddate
	}
	return nil
}

func init() {
	proto.RegisterType((*TMcoinExrate)(nil), "usercenter.TMcoinExrate")
}

func init() {
	proto.RegisterFile("usercenter/t_mcoinexrate.proto", fileDescriptor_t_mcoinexrate_584c554a65e27887)
}

var fileDescriptor_t_mcoinexrate_584c554a65e27887 = []byte{
	// 338 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x91, 0x3f, 0x6b, 0xe3, 0x30,
	0x18, 0xc6, 0x49, 0x72, 0x97, 0x73, 0xe4, 0x70, 0x47, 0x7c, 0x8b, 0x49, 0xa1, 0x4d, 0x3b, 0x85,
	0x0e, 0x36, 0xb4, 0xd0, 0x25, 0x5b, 0x69, 0xe9, 0xd2, 0x74, 0x08, 0xe9, 0xd2, 0xc5, 0xc8, 0xd6,
	0x1b, 0x47, 0x60, 0x49, 0x46, 0x7f, 0x20, 0xf9, 0x50, 0xfd, 0x8e, 0x45, 0xaf, 0x1c, 0xa7, 0x5b,
	0x37, 0xfb, 0xf9, 0xfd, 0xfc, 0x3c, 0x46, 0x22, 0x97, 0xce, 0x80, 0xae, 0x40, 0x5a, 0xd0, 0xb9,
	0x2d, 0x44, 0xa5, 0xb8, 0x84, 0x83, 0xa6, 0x16, 0xb2, 0x56, 0x2b, 0xab, 0x12, 0x72, 0xe6, 0xf3,
	0x55, 0xcd, 0xed, 0xde, 0x95, 0x59, 0xa5, 0x44, 0x5e, 0xab, 0x86, 0xca, 0x3a, 0x47, 0xa9, 0x74,
	0xbb, 0xbc, 0xb5, 0xc7, 0x16, 0x4c, 0x6e, 0xb9, 0x00, 0x63, 0xa9, 0x68, 0xcf, 0x4f, 0xa1, 0xe8,
	0xe6, 0x73, 0x44, 0xa6, 0xdb, 0xb5, 0xef, 0x7f, 0xc6, 0xfe, 0xe4, 0x2f, 0x19, 0x72, 0x96, 0x0e,
	0x16, 0x83, 0xe5, 0x64, 0x33, 0xe4, 0x2c, 0xb9, 0x26, 0x53, 0x01, 0xa2, 0x04, 0x5d, 0xd4, 0x9a,
	0x32, 0x48, 0x87, 0x48, 0xe2, 0x90, 0xbd, 0xf8, 0x28, 0xb9, 0x20, 0x13, 0x53, 0x29, 0x0d, 0x85,
	0x74, 0x22, 0x1d, 0x21, 0x8f, 0x30, 0x78, 0x73, 0xc2, 0x43, 0xfc, 0x7d, 0x84, 0xbf, 0x02, 0xc4,
	0xa0, 0x83, 0x8c, 0x1e, 0x8b, 0x86, 0x0b, 0x6e, 0xd3, 0xdf, 0x01, 0x32, 0x7a, 0x7c, 0xf5, 0xef,
	0x7e, 0xb9, 0x05, 0x6d, 0x94, 0xec, 0xf8, 0x38, 0x2c, 0x87, 0x2c, 0x28, 0xb7, 0x64, 0x56, 0x39,
	0xad, 0x41, 0x76, 0x67, 0x84, 0x23, 0x7f, 0xd0, 0xfb, 0xd7, 0x81, 0xf5, 0x69, 0x2b, 0x23, 0xff,
	0xe1, 0x50, 0xed, 0xa9, 0xac, 0x81, 0x7d, 0xb3, 0x23, 0xb4, 0x67, 0x3d, 0xea, 0xfd, 0x15, 0x89,
	0x2b, 0x0d, 0xd4, 0x42, 0xc1, 0xa8, 0x85, 0x74, 0xb2, 0x18, 0x2c, 0xe3, 0xbb, 0x79, 0x56, 0x2b,
	0x55, 0x37, 0xdd, 0x35, 0x94, 0x6e, 0x97, 0x6d, 0x4f, 0x07, 0xba, 0x21, 0x41, 0x7f, 0xf2, 0xa7,
	0x78, 0xd5, 0x7f, 0xec, 0x2f, 0x2a, 0x25, 0x38, 0xd2, 0x09, 0xef, 0x06, 0x74, 0xf2, 0x40, 0xa2,
	0xc6, 0xb5, 0x0c, 0xab, 0xe3, 0x1f, 0xab, 0x7b, 0xf7, 0x31, 0xfa, 0x18, 0x0b, 0xc5, 0xa0, 0x31,
	0xe5, 0x18, 0xbd, 0xfb, 0xaf, 0x00, 0x00, 0x00, 0xff, 0xff, 0xd1, 0x0f, 0x42, 0x14, 0x2b, 0x02,
	0x00, 0x00,
}
