// Code generated by protoc-gen-go. DO NOT EDIT.
// source: usercenter/t_membersignconfig.proto

package models

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "github.com/golang/protobuf/ptypes/timestamp"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type TMemberSignConfig struct {
	ActionScoreId        string   `protobuf:"bytes,1,opt,name=action_score_id,json=actionScoreId,proto3" json:"action_score_id,omitempty"`
	MemberGrade          string   `protobuf:"bytes,2,opt,name=member_grade,json=memberGrade,proto3" json:"member_grade,omitempty"`
	FirstDayPoint        string   `protobuf:"bytes,3,opt,name=first_day_point,json=firstDayPoint,proto3" json:"first_day_point,omitempty"`
	SecondDayPoint       string   `protobuf:"bytes,4,opt,name=second_day_point,json=secondDayPoint,proto3" json:"second_day_point,omitempty"`
	ThirdDayPoint        string   `protobuf:"bytes,5,opt,name=third_day_point,json=thirdDayPoint,proto3" json:"third_day_point,omitempty"`
	FourthDayPoint       string   `protobuf:"bytes,6,opt,name=fourth_day_point,json=fourthDayPoint,proto3" json:"fourth_day_point,omitempty"`
	FifthDayPoint        string   `protobuf:"bytes,7,opt,name=fifth_day_point,json=fifthDayPoint,proto3" json:"fifth_day_point,omitempty"`
	SixDayPoint          string   `protobuf:"bytes,8,opt,name=six_day_point,json=sixDayPoint,proto3" json:"six_day_point,omitempty"`
	SeventhDayChance1    string   `protobuf:"bytes,9,opt,name=seventh_day_chance1,json=seventhDayChance1,proto3" json:"seventh_day_chance1,omitempty"`
	SeventhDayPoint1     string   `protobuf:"bytes,10,opt,name=seventh_day_point1,json=seventhDayPoint1,proto3" json:"seventh_day_point1,omitempty"`
	SeventhDayChance2    string   `protobuf:"bytes,11,opt,name=seventh_day_chance2,json=seventhDayChance2,proto3" json:"seventh_day_chance2,omitempty"`
	SeventhDayPoint2     string   `protobuf:"bytes,12,opt,name=seventh_day_point2,json=seventhDayPoint2,proto3" json:"seventh_day_point2,omitempty"`
	SeventhDayChance3    string   `protobuf:"bytes,13,opt,name=seventh_day_chance3,json=seventhDayChance3,proto3" json:"seventh_day_chance3,omitempty"`
	SeventhDayPoint3     string   `protobuf:"bytes,14,opt,name=seventh_day_point3,json=seventhDayPoint3,proto3" json:"seventh_day_point3,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TMemberSignConfig) Reset()         { *m = TMemberSignConfig{} }
func (m *TMemberSignConfig) String() string { return proto.CompactTextString(m) }
func (*TMemberSignConfig) ProtoMessage()    {}
func (*TMemberSignConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_t_membersignconfig_42c99e8212ae2350, []int{0}
}
func (m *TMemberSignConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TMemberSignConfig.Unmarshal(m, b)
}
func (m *TMemberSignConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TMemberSignConfig.Marshal(b, m, deterministic)
}
func (dst *TMemberSignConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TMemberSignConfig.Merge(dst, src)
}
func (m *TMemberSignConfig) XXX_Size() int {
	return xxx_messageInfo_TMemberSignConfig.Size(m)
}
func (m *TMemberSignConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_TMemberSignConfig.DiscardUnknown(m)
}

var xxx_messageInfo_TMemberSignConfig proto.InternalMessageInfo

func (m *TMemberSignConfig) GetActionScoreId() string {
	if m != nil {
		return m.ActionScoreId
	}
	return ""
}

func (m *TMemberSignConfig) GetMemberGrade() string {
	if m != nil {
		return m.MemberGrade
	}
	return ""
}

func (m *TMemberSignConfig) GetFirstDayPoint() string {
	if m != nil {
		return m.FirstDayPoint
	}
	return ""
}

func (m *TMemberSignConfig) GetSecondDayPoint() string {
	if m != nil {
		return m.SecondDayPoint
	}
	return ""
}

func (m *TMemberSignConfig) GetThirdDayPoint() string {
	if m != nil {
		return m.ThirdDayPoint
	}
	return ""
}

func (m *TMemberSignConfig) GetFourthDayPoint() string {
	if m != nil {
		return m.FourthDayPoint
	}
	return ""
}

func (m *TMemberSignConfig) GetFifthDayPoint() string {
	if m != nil {
		return m.FifthDayPoint
	}
	return ""
}

func (m *TMemberSignConfig) GetSixDayPoint() string {
	if m != nil {
		return m.SixDayPoint
	}
	return ""
}

func (m *TMemberSignConfig) GetSeventhDayChance1() string {
	if m != nil {
		return m.SeventhDayChance1
	}
	return ""
}

func (m *TMemberSignConfig) GetSeventhDayPoint1() string {
	if m != nil {
		return m.SeventhDayPoint1
	}
	return ""
}

func (m *TMemberSignConfig) GetSeventhDayChance2() string {
	if m != nil {
		return m.SeventhDayChance2
	}
	return ""
}

func (m *TMemberSignConfig) GetSeventhDayPoint2() string {
	if m != nil {
		return m.SeventhDayPoint2
	}
	return ""
}

func (m *TMemberSignConfig) GetSeventhDayChance3() string {
	if m != nil {
		return m.SeventhDayChance3
	}
	return ""
}

func (m *TMemberSignConfig) GetSeventhDayPoint3() string {
	if m != nil {
		return m.SeventhDayPoint3
	}
	return ""
}

func init() {
	proto.RegisterType((*TMemberSignConfig)(nil), "usercenter.TMemberSignConfig")
}

func init() {
	proto.RegisterFile("usercenter/t_membersignconfig.proto", fileDescriptor_t_membersignconfig_42c99e8212ae2350)
}

var fileDescriptor_t_membersignconfig_42c99e8212ae2350 = []byte{
	// 355 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0xd2, 0x4f, 0x6b, 0xf2, 0x30,
	0x00, 0xc7, 0x71, 0x7c, 0x1e, 0x1f, 0x1f, 0x8d, 0xff, 0xbb, 0x4b, 0xd8, 0x69, 0x73, 0x20, 0x1e,
	0x86, 0xc5, 0xf6, 0xb8, 0xdb, 0x14, 0xc6, 0x0e, 0x83, 0x31, 0x77, 0xda, 0xa5, 0xa4, 0x69, 0x9a,
	0x06, 0x6c, 0x52, 0x92, 0x74, 0xd8, 0x77, 0xbc, 0x97, 0x31, 0x9a, 0x38, 0xcd, 0x20, 0x37, 0xf9,
	0xe5, 0xcb, 0x27, 0x11, 0x0a, 0xee, 0x6a, 0x45, 0x24, 0x26, 0x5c, 0x13, 0x19, 0xea, 0xa4, 0x24,
	0x65, 0x4a, 0xa4, 0x62, 0x94, 0x63, 0xc1, 0x73, 0x46, 0xd7, 0x95, 0x14, 0x5a, 0x04, 0xe0, 0x12,
	0x5d, 0x3f, 0x50, 0xa6, 0x8b, 0x3a, 0x5d, 0x63, 0x51, 0x86, 0x54, 0x1c, 0x10, 0xa7, 0xa1, 0x89,
	0xd2, 0x3a, 0x0f, 0x2b, 0xdd, 0x54, 0x44, 0x85, 0x9a, 0x95, 0x44, 0x69, 0x54, 0x56, 0x97, 0x5f,
	0x16, 0x5a, 0x7c, 0x75, 0xc1, 0xfc, 0xfd, 0xc5, 0x5c, 0xb2, 0x67, 0x94, 0x6f, 0xcd, 0x25, 0xc1,
	0x12, 0x4c, 0x11, 0xd6, 0x4c, 0xf0, 0x44, 0x61, 0x21, 0x49, 0xc2, 0x32, 0xd8, 0xb9, 0xe9, 0xac,
	0x06, 0x6f, 0x63, 0x3b, 0xef, 0xdb, 0xf5, 0x39, 0x0b, 0x6e, 0xc1, 0xc8, 0x3e, 0x30, 0xa1, 0x12,
	0x65, 0x04, 0xfe, 0x31, 0xd1, 0xd0, 0x6e, 0x4f, 0xed, 0xd4, 0x52, 0x39, 0x93, 0x4a, 0x27, 0x19,
	0x6a, 0x92, 0x4a, 0x30, 0xae, 0xe1, 0x5f, 0x4b, 0x99, 0x79, 0x87, 0x9a, 0xd7, 0x76, 0x0c, 0x56,
	0x60, 0xa6, 0x08, 0x16, 0x3c, 0x73, 0xc2, 0xae, 0x09, 0x27, 0x76, 0x3f, 0x97, 0x4b, 0x30, 0xd5,
	0x05, 0x93, 0x6e, 0xf8, 0xcf, 0x8a, 0x66, 0x76, 0xc5, 0x5c, 0xd4, 0x52, 0x17, 0x4e, 0xd8, 0xb3,
	0xa2, 0xdd, 0x5d, 0x31, 0x67, 0xf9, 0xaf, 0xf0, 0xff, 0xcf, 0x1b, 0x73, 0xa7, 0x5b, 0x80, 0xb1,
	0x62, 0x47, 0xa7, 0xea, 0xdb, 0xff, 0xab, 0xd8, 0xf1, 0xdc, 0xac, 0xc1, 0x95, 0x22, 0x9f, 0x84,
	0x9f, 0x34, 0x5c, 0x20, 0x8e, 0xc9, 0x06, 0x0e, 0x4c, 0x39, 0x3f, 0x1d, 0xed, 0x50, 0xb3, 0xb5,
	0x07, 0xc1, 0x3d, 0x08, 0xdc, 0xde, 0xb8, 0x1b, 0x08, 0x4c, 0x3e, 0xbb, 0xe4, 0x06, 0xdf, 0xf8,
	0xf5, 0x08, 0x0e, 0xfd, 0x7a, 0xe4, 0xd5, 0x23, 0x38, 0xf2, 0xea, 0x91, 0x5f, 0x8f, 0xe1, 0xd8,
	0xaf, 0xc7, 0x5e, 0x3d, 0x86, 0x13, 0xaf, 0x1e, 0x3f, 0xf6, 0x3f, 0x7a, 0xa5, 0xc8, 0xc8, 0x41,
	0xa5, 0x3d, 0xf3, 0xed, 0xc5, 0xdf, 0x01, 0x00, 0x00, 0xff, 0xff, 0x58, 0x8d, 0x87, 0x5b, 0xeb,
	0x02, 0x00, 0x00,
}
