// Code generated by protoc-gen-go. DO NOT EDIT.
// source: usercenter/t_mmzerosubscribe.proto

package models

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "github.com/golang/protobuf/ptypes/timestamp"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type TMmZeroSubscribe struct {
	Mobile               string   `protobuf:"bytes,1,opt,name=mobile,proto3" json:"mobile,omitempty"`
	PayCode              string   `protobuf:"bytes,2,opt,name=pay_code,json=payCode,proto3" json:"pay_code,omitempty"`
	RightsId             string   `protobuf:"bytes,3,opt,name=rights_id,json=rightsId,proto3" json:"rights_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TMmZeroSubscribe) Reset()         { *m = TMmZeroSubscribe{} }
func (m *TMmZeroSubscribe) String() string { return proto.CompactTextString(m) }
func (*TMmZeroSubscribe) ProtoMessage()    {}
func (*TMmZeroSubscribe) Descriptor() ([]byte, []int) {
	return fileDescriptor_t_mmzerosubscribe_3bf35fbf393b0f3a, []int{0}
}
func (m *TMmZeroSubscribe) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TMmZeroSubscribe.Unmarshal(m, b)
}
func (m *TMmZeroSubscribe) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TMmZeroSubscribe.Marshal(b, m, deterministic)
}
func (dst *TMmZeroSubscribe) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TMmZeroSubscribe.Merge(dst, src)
}
func (m *TMmZeroSubscribe) XXX_Size() int {
	return xxx_messageInfo_TMmZeroSubscribe.Size(m)
}
func (m *TMmZeroSubscribe) XXX_DiscardUnknown() {
	xxx_messageInfo_TMmZeroSubscribe.DiscardUnknown(m)
}

var xxx_messageInfo_TMmZeroSubscribe proto.InternalMessageInfo

func (m *TMmZeroSubscribe) GetMobile() string {
	if m != nil {
		return m.Mobile
	}
	return ""
}

func (m *TMmZeroSubscribe) GetPayCode() string {
	if m != nil {
		return m.PayCode
	}
	return ""
}

func (m *TMmZeroSubscribe) GetRightsId() string {
	if m != nil {
		return m.RightsId
	}
	return ""
}

func init() {
	proto.RegisterType((*TMmZeroSubscribe)(nil), "usercenter.TMmZeroSubscribe")
}

func init() {
	proto.RegisterFile("usercenter/t_mmzerosubscribe.proto", fileDescriptor_t_mmzerosubscribe_3bf35fbf393b0f3a)
}

var fileDescriptor_t_mmzerosubscribe_3bf35fbf393b0f3a = []byte{
	// 195 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x44, 0x8d, 0xaf, 0x4f, 0xc6, 0x30,
	0x10, 0x40, 0xf3, 0x41, 0x32, 0xf6, 0x55, 0x91, 0x0a, 0x32, 0xc0, 0x90, 0x29, 0xd4, 0x2a, 0x90,
	0x38, 0x50, 0x08, 0x0c, 0xa0, 0x66, 0x96, 0xfe, 0x38, 0xba, 0x26, 0xbb, 0x5d, 0xd3, 0x5e, 0xc5,
	0xf8, 0xeb, 0x49, 0x3a, 0xc8, 0xdc, 0xdd, 0xbd, 0x97, 0x7b, 0xa2, 0x2f, 0x19, 0x92, 0x85, 0x95,
	0x21, 0x29, 0x9e, 0x10, 0x7f, 0x20, 0x51, 0x2e, 0x26, 0xdb, 0x14, 0x0c, 0x0c, 0x31, 0x11, 0x93,
	0x14, 0x87, 0x73, 0xf7, 0xec, 0x03, 0xcf, 0xc5, 0x0c, 0x96, 0x50, 0x79, 0x5a, 0xf4, 0xea, 0x55,
	0x95, 0x4c, 0xf9, 0x56, 0x91, 0xb7, 0x08, 0x59, 0x71, 0x40, 0xc8, 0xac, 0x31, 0x1e, 0xd3, 0xfe,
	0xa8, 0x37, 0xe2, 0xfa, 0xeb, 0x1d, 0x47, 0x48, 0xf4, 0xf9, 0x9f, 0x90, 0x37, 0xa2, 0x41, 0x32,
	0x61, 0x81, 0xee, 0xf4, 0x70, 0x7a, 0x3c, 0x7f, 0xfc, 0x6d, 0xf2, 0x56, 0xb4, 0x51, 0x6f, 0x93,
	0x25, 0x07, 0xdd, 0x45, 0x25, 0x57, 0x51, 0x6f, 0xaf, 0xe4, 0x40, 0xde, 0x8b, 0x73, 0x0a, 0x7e,
	0xe6, 0x3c, 0x05, 0xd7, 0x5d, 0x56, 0xd6, 0xee, 0x87, 0x37, 0xf7, 0xd2, 0x8e, 0x0d, 0x92, 0x83,
	0x25, 0x9b, 0xa6, 0x46, 0x9f, 0x7e, 0x03, 0x00, 0x00, 0xff, 0xff, 0x60, 0x79, 0x96, 0x04, 0xe3,
	0x00, 0x00, 0x00,
}
