// Code generated by protoc-gen-go. DO NOT EDIT.
// source: usercenter/t_scoreexchange.proto

package models

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import timestamp "github.com/golang/protobuf/ptypes/timestamp"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type TScoreExchange struct {
	Id                   string               `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Mobile               string               `protobuf:"bytes,2,opt,name=mobile,proto3" json:"mobile,omitempty"`
	ScoreNum             string               `protobuf:"bytes,3,opt,name=score_num,json=scoreNum,proto3" json:"score_num,omitempty"`
	McoinNum             string               `protobuf:"bytes,4,opt,name=mcoin_num,json=mcoinNum,proto3" json:"mcoin_num,omitempty"`
	CreateDate           *timestamp.Timestamp `protobuf:"bytes,5,opt,name=create_date,json=createDate,proto3" json:"create_date,omitempty"`
	Descs                string               `protobuf:"bytes,6,opt,name=descs,proto3" json:"descs,omitempty"`
	GoodsId              string               `protobuf:"bytes,7,opt,name=goods_id,json=goodsId,proto3" json:"goods_id,omitempty"`
	GoodsNum             string               `protobuf:"bytes,8,opt,name=goods_num,json=goodsNum,proto3" json:"goods_num,omitempty"`
	PartitionId          string               `protobuf:"bytes,9,opt,name=partition_id,json=partitionId,proto3" json:"partition_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *TScoreExchange) Reset()         { *m = TScoreExchange{} }
func (m *TScoreExchange) String() string { return proto.CompactTextString(m) }
func (*TScoreExchange) ProtoMessage()    {}
func (*TScoreExchange) Descriptor() ([]byte, []int) {
	return fileDescriptor_t_scoreexchange_e7e43a92ee69792c, []int{0}
}
func (m *TScoreExchange) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TScoreExchange.Unmarshal(m, b)
}
func (m *TScoreExchange) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TScoreExchange.Marshal(b, m, deterministic)
}
func (dst *TScoreExchange) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TScoreExchange.Merge(dst, src)
}
func (m *TScoreExchange) XXX_Size() int {
	return xxx_messageInfo_TScoreExchange.Size(m)
}
func (m *TScoreExchange) XXX_DiscardUnknown() {
	xxx_messageInfo_TScoreExchange.DiscardUnknown(m)
}

var xxx_messageInfo_TScoreExchange proto.InternalMessageInfo

func (m *TScoreExchange) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *TScoreExchange) GetMobile() string {
	if m != nil {
		return m.Mobile
	}
	return ""
}

func (m *TScoreExchange) GetScoreNum() string {
	if m != nil {
		return m.ScoreNum
	}
	return ""
}

func (m *TScoreExchange) GetMcoinNum() string {
	if m != nil {
		return m.McoinNum
	}
	return ""
}

func (m *TScoreExchange) GetCreateDate() *timestamp.Timestamp {
	if m != nil {
		return m.CreateDate
	}
	return nil
}

func (m *TScoreExchange) GetDescs() string {
	if m != nil {
		return m.Descs
	}
	return ""
}

func (m *TScoreExchange) GetGoodsId() string {
	if m != nil {
		return m.GoodsId
	}
	return ""
}

func (m *TScoreExchange) GetGoodsNum() string {
	if m != nil {
		return m.GoodsNum
	}
	return ""
}

func (m *TScoreExchange) GetPartitionId() string {
	if m != nil {
		return m.PartitionId
	}
	return ""
}

func init() {
	proto.RegisterType((*TScoreExchange)(nil), "usercenter.TScoreExchange")
}

func init() {
	proto.RegisterFile("usercenter/t_scoreexchange.proto", fileDescriptor_t_scoreexchange_e7e43a92ee69792c)
}

var fileDescriptor_t_scoreexchange_e7e43a92ee69792c = []byte{
	// 292 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x44, 0x8f, 0x31, 0x4f, 0xf3, 0x30,
	0x10, 0x86, 0xd5, 0x7c, 0x5f, 0xd3, 0xd4, 0x45, 0x1d, 0x22, 0x84, 0x42, 0x59, 0x0a, 0x53, 0xa7,
	0x44, 0x82, 0xb1, 0x1b, 0x82, 0xa1, 0x0b, 0x43, 0xe9, 0xc4, 0x12, 0x39, 0xf6, 0xd5, 0xb5, 0x14,
	0xe7, 0xa2, 0xf8, 0x22, 0xc1, 0xbf, 0xe1, 0xa7, 0x22, 0x9f, 0x0b, 0xdd, 0x72, 0xef, 0xf3, 0xe6,
	0xee, 0xb1, 0x58, 0x8f, 0x1e, 0x06, 0x05, 0x1d, 0xc1, 0x50, 0x51, 0xed, 0x15, 0x0e, 0x00, 0x9f,
	0xea, 0x24, 0x3b, 0x03, 0x65, 0x3f, 0x20, 0x61, 0x2e, 0x2e, 0x8d, 0xd5, 0xd6, 0x58, 0x3a, 0x8d,
	0x4d, 0xa9, 0xd0, 0x55, 0x06, 0x5b, 0xd9, 0x99, 0x8a, 0x4b, 0xcd, 0x78, 0xac, 0x7a, 0xfa, 0xea,
	0xc1, 0x57, 0x64, 0x1d, 0x78, 0x92, 0xae, 0xbf, 0x7c, 0xc5, 0x45, 0x0f, 0xdf, 0x89, 0x58, 0x1e,
	0xde, 0xc3, 0x85, 0xd7, 0xf3, 0x85, 0x7c, 0x29, 0x12, 0xab, 0x8b, 0xc9, 0x7a, 0xb2, 0x99, 0xef,
	0x13, 0xab, 0xf3, 0x1b, 0x91, 0x3a, 0x6c, 0x6c, 0x0b, 0x45, 0xc2, 0xd9, 0x79, 0xca, 0xef, 0xc4,
	0x9c, 0xd5, 0xea, 0x6e, 0x74, 0xc5, 0x3f, 0x46, 0x19, 0x07, 0x6f, 0xa3, 0x0b, 0xd0, 0x29, 0xb4,
	0x1d, 0xc3, 0xff, 0x11, 0x72, 0x10, 0xe0, 0x56, 0x2c, 0xd4, 0x00, 0x92, 0xa0, 0xd6, 0x92, 0xa0,
	0x98, 0xae, 0x27, 0x9b, 0xc5, 0xe3, 0xaa, 0x34, 0x88, 0xa6, 0x3d, 0xbf, 0xb0, 0x19, 0x8f, 0xe5,
	0xe1, 0xd7, 0x75, 0x2f, 0x62, 0xfd, 0x45, 0x12, 0xe4, 0xd7, 0x62, 0xaa, 0xc1, 0x2b, 0x5f, 0xa4,
	0xbc, 0x35, 0x0e, 0xf9, 0xad, 0xc8, 0x0c, 0xa2, 0xf6, 0xb5, 0xd5, 0xc5, 0x8c, 0xc1, 0x8c, 0xe7,
	0x9d, 0x0e, 0x2a, 0x11, 0x05, 0x95, 0x2c, 0xaa, 0x70, 0x10, 0x54, 0xee, 0xc5, 0x55, 0x2f, 0x07,
	0xb2, 0x64, 0xb1, 0x0b, 0xff, 0xce, 0x99, 0x2f, 0xfe, 0xb2, 0x9d, 0x7e, 0xce, 0x3e, 0x52, 0x87,
	0x1a, 0x5a, 0xdf, 0xa4, 0xac, 0xf6, 0xf4, 0x13, 0x00, 0x00, 0xff, 0xff, 0x28, 0x96, 0x1a, 0xfd,
	0xa0, 0x01, 0x00, 0x00,
}
