// Code generated by protoc-gen-go. DO NOT EDIT.
// source: usercenter/t_taskexcute.proto

package models

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import timestamp "github.com/golang/protobuf/ptypes/timestamp"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type TTaskExcute struct {
	Taskid               string               `protobuf:"bytes,1,opt,name=taskid,proto3" json:"taskid,omitempty"`
	Reqseq               string               `protobuf:"bytes,2,opt,name=reqseq,proto3" json:"reqseq,omitempty"`
	Reqdate              *timestamp.Timestamp `protobuf:"bytes,3,opt,name=reqdate,proto3" json:"reqdate,omitempty"`
	Respdate             *timestamp.Timestamp `protobuf:"bytes,4,opt,name=respdate,proto3" json:"respdate,omitempty"`
	Costtime             string               `protobuf:"bytes,5,opt,name=costtime,proto3" json:"costtime,omitempty"`
	Respcontent          string               `protobuf:"bytes,6,opt,name=respcontent,proto3" json:"respcontent,omitempty"`
	Retcode              string               `protobuf:"bytes,7,opt,name=retcode,proto3" json:"retcode,omitempty"`
	Errordesc            string               `protobuf:"bytes,8,opt,name=errordesc,proto3" json:"errordesc,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *TTaskExcute) Reset()         { *m = TTaskExcute{} }
func (m *TTaskExcute) String() string { return proto.CompactTextString(m) }
func (*TTaskExcute) ProtoMessage()    {}
func (*TTaskExcute) Descriptor() ([]byte, []int) {
	return fileDescriptor_t_taskexcute_ad0973e206cf3a6c, []int{0}
}
func (m *TTaskExcute) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TTaskExcute.Unmarshal(m, b)
}
func (m *TTaskExcute) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TTaskExcute.Marshal(b, m, deterministic)
}
func (dst *TTaskExcute) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TTaskExcute.Merge(dst, src)
}
func (m *TTaskExcute) XXX_Size() int {
	return xxx_messageInfo_TTaskExcute.Size(m)
}
func (m *TTaskExcute) XXX_DiscardUnknown() {
	xxx_messageInfo_TTaskExcute.DiscardUnknown(m)
}

var xxx_messageInfo_TTaskExcute proto.InternalMessageInfo

func (m *TTaskExcute) GetTaskid() string {
	if m != nil {
		return m.Taskid
	}
	return ""
}

func (m *TTaskExcute) GetReqseq() string {
	if m != nil {
		return m.Reqseq
	}
	return ""
}

func (m *TTaskExcute) GetReqdate() *timestamp.Timestamp {
	if m != nil {
		return m.Reqdate
	}
	return nil
}

func (m *TTaskExcute) GetRespdate() *timestamp.Timestamp {
	if m != nil {
		return m.Respdate
	}
	return nil
}

func (m *TTaskExcute) GetCosttime() string {
	if m != nil {
		return m.Costtime
	}
	return ""
}

func (m *TTaskExcute) GetRespcontent() string {
	if m != nil {
		return m.Respcontent
	}
	return ""
}

func (m *TTaskExcute) GetRetcode() string {
	if m != nil {
		return m.Retcode
	}
	return ""
}

func (m *TTaskExcute) GetErrordesc() string {
	if m != nil {
		return m.Errordesc
	}
	return ""
}

func init() {
	proto.RegisterType((*TTaskExcute)(nil), "usercenter.TTaskExcute")
}

func init() {
	proto.RegisterFile("usercenter/t_taskexcute.proto", fileDescriptor_t_taskexcute_ad0973e206cf3a6c)
}

var fileDescriptor_t_taskexcute_ad0973e206cf3a6c = []byte{
	// 267 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x8f, 0xbf, 0x4e, 0xbc, 0x40,
	0x10, 0xc7, 0xc3, 0xfd, 0x7e, 0x72, 0xdc, 0xd2, 0x6d, 0x61, 0x36, 0x44, 0x13, 0x62, 0x75, 0x15,
	0x24, 0x6a, 0x6c, 0xec, 0x4c, 0x7c, 0x81, 0x0b, 0x95, 0x8d, 0x81, 0x65, 0x0e, 0xc9, 0x01, 0x03,
	0x3b, 0xb3, 0x89, 0x3e, 0x8e, 0x6f, 0x6a, 0x76, 0x39, 0x0e, 0x3b, 0xbb, 0xfd, 0xfe, 0x99, 0x99,
	0xcf, 0x8a, 0x5b, 0x4b, 0x60, 0x34, 0x0c, 0x0c, 0x26, 0xe7, 0x77, 0x2e, 0xe9, 0x04, 0x9f, 0xda,
	0x32, 0x64, 0xa3, 0x41, 0x46, 0x29, 0xd6, 0x38, 0x79, 0x6e, 0x5a, 0xfe, 0xb0, 0x55, 0xa6, 0xb1,
	0xcf, 0x1b, 0xec, 0xca, 0xa1, 0xc9, 0x7d, 0xa9, 0xb2, 0xc7, 0x7c, 0xe4, 0xaf, 0x11, 0x28, 0xe7,
	0xb6, 0x07, 0xe2, 0xb2, 0x1f, 0xd7, 0xd7, 0xbc, 0xe8, 0xee, 0x7b, 0x23, 0xe2, 0xa2, 0x28, 0xe9,
	0xf4, 0xea, 0xd7, 0xcb, 0x6b, 0x11, 0xba, 0x63, 0x6d, 0xad, 0x82, 0x34, 0xd8, 0xef, 0x0e, 0x67,
	0xe5, 0x7c, 0x03, 0x13, 0xc1, 0xa4, 0x36, 0xb3, 0x3f, 0x2b, 0xf9, 0x28, 0xb6, 0x06, 0xa6, 0xba,
	0x64, 0x50, 0xff, 0xd2, 0x60, 0x1f, 0xdf, 0x27, 0x59, 0x83, 0xd8, 0x74, 0x67, 0xd0, 0xca, 0x1e,
	0xb3, 0x62, 0x39, 0x79, 0x58, 0xaa, 0xf2, 0x49, 0x44, 0x06, 0x68, 0xf4, 0x63, 0xff, 0xff, 0x1c,
	0xbb, 0x74, 0x65, 0x22, 0x22, 0x8d, 0xc4, 0xee, 0x13, 0xea, 0xca, 0x73, 0x5c, 0xb4, 0x4c, 0x45,
	0xec, 0x7a, 0x1a, 0x07, 0x86, 0x81, 0x55, 0xe8, 0xe3, 0xdf, 0x96, 0x54, 0x8e, 0x95, 0x35, 0xd6,
	0xa0, 0xb6, 0x3e, 0x5d, 0xa4, 0xbc, 0x11, 0x3b, 0x30, 0x06, 0x4d, 0x0d, 0xa4, 0x55, 0xe4, 0xb3,
	0xd5, 0x78, 0x89, 0xde, 0xc2, 0x1e, 0x6b, 0xe8, 0xa8, 0x0a, 0x3d, 0xdd, 0xc3, 0x4f, 0x00, 0x00,
	0x00, 0xff, 0xff, 0xc7, 0xc6, 0x51, 0xab, 0x9e, 0x01, 0x00, 0x00,
}
