// Code generated by protoc-gen-go. DO NOT EDIT.
// source: usercenter/t_taskstrategy.proto

package models

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "github.com/golang/protobuf/ptypes/timestamp"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type TTaskStrategy struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Interval             string   `protobuf:"bytes,2,opt,name=interval,proto3" json:"interval,omitempty"`
	Unit                 string   `protobuf:"bytes,3,opt,name=unit,proto3" json:"unit,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TTaskStrategy) Reset()         { *m = TTaskStrategy{} }
func (m *TTaskStrategy) String() string { return proto.CompactTextString(m) }
func (*TTaskStrategy) ProtoMessage()    {}
func (*TTaskStrategy) Descriptor() ([]byte, []int) {
	return fileDescriptor_t_taskstrategy_6ffbcd230e1fee8d, []int{0}
}
func (m *TTaskStrategy) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TTaskStrategy.Unmarshal(m, b)
}
func (m *TTaskStrategy) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TTaskStrategy.Marshal(b, m, deterministic)
}
func (dst *TTaskStrategy) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TTaskStrategy.Merge(dst, src)
}
func (m *TTaskStrategy) XXX_Size() int {
	return xxx_messageInfo_TTaskStrategy.Size(m)
}
func (m *TTaskStrategy) XXX_DiscardUnknown() {
	xxx_messageInfo_TTaskStrategy.DiscardUnknown(m)
}

var xxx_messageInfo_TTaskStrategy proto.InternalMessageInfo

func (m *TTaskStrategy) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *TTaskStrategy) GetInterval() string {
	if m != nil {
		return m.Interval
	}
	return ""
}

func (m *TTaskStrategy) GetUnit() string {
	if m != nil {
		return m.Unit
	}
	return ""
}

func init() {
	proto.RegisterType((*TTaskStrategy)(nil), "usercenter.TTaskStrategy")
}

func init() {
	proto.RegisterFile("usercenter/t_taskstrategy.proto", fileDescriptor_t_taskstrategy_6ffbcd230e1fee8d)
}

var fileDescriptor_t_taskstrategy_6ffbcd230e1fee8d = []byte{
	// 178 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x44, 0x8d, 0xb1, 0xca, 0xc2, 0x30,
	0x14, 0x85, 0x69, 0xff, 0x9f, 0x52, 0x03, 0x3a, 0x64, 0x2a, 0x5d, 0x14, 0x27, 0xa7, 0x66, 0x70,
	0x74, 0xf3, 0x05, 0x04, 0xed, 0xe4, 0x22, 0x69, 0x7b, 0x8d, 0xa1, 0x4d, 0x13, 0x72, 0x6f, 0x84,
	0xbe, 0xbd, 0x18, 0xc5, 0x6e, 0xe7, 0x1c, 0x0e, 0xdf, 0xc7, 0xd6, 0x01, 0xc1, 0xb7, 0x30, 0x12,
	0x78, 0x41, 0x37, 0x92, 0xd8, 0x23, 0x79, 0x49, 0xa0, 0xa6, 0xca, 0x79, 0x4b, 0x96, 0xb3, 0xf9,
	0x50, 0x1e, 0x94, 0xa6, 0x47, 0x68, 0xaa, 0xd6, 0x1a, 0xa1, 0xec, 0x20, 0x47, 0x25, 0xe2, 0xa9,
	0x09, 0x77, 0xe1, 0x68, 0x72, 0x80, 0x82, 0xb4, 0x01, 0x24, 0x69, 0xdc, 0x9c, 0x3e, 0xa0, 0xed,
	0x89, 0x2d, 0xeb, 0x5a, 0x62, 0x7f, 0xf9, 0xf2, 0xf9, 0x8a, 0xa5, 0xba, 0x2b, 0x92, 0x4d, 0xb2,
	0x5b, 0x9c, 0x53, 0xdd, 0xf1, 0x92, 0xe5, 0xfa, 0xad, 0x79, 0xca, 0xa1, 0x48, 0xe3, 0xfa, 0xeb,
	0x9c, 0xb3, 0xff, 0x30, 0x6a, 0x2a, 0xfe, 0xe2, 0x1e, 0xf3, 0x31, 0xbf, 0x66, 0xc6, 0x76, 0x30,
	0x60, 0x93, 0x45, 0xc3, 0xfe, 0x15, 0x00, 0x00, 0xff, 0xff, 0xdb, 0x8c, 0x22, 0x50, 0xcd, 0x00,
	0x00, 0x00,
}
