// Code generated by protoc-gen-go. DO NOT EDIT.
// source: usercenter/t_userportrait.proto

package models

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import timestamp "github.com/golang/protobuf/ptypes/timestamp"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type TUserPortrait struct {
	Id                   string               `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Mobile               string               `protobuf:"bytes,2,opt,name=mobile,proto3" json:"mobile,omitempty"`
	NikeName             string               `protobuf:"bytes,3,opt,name=nike_name,json=nikeName,proto3" json:"nike_name,omitempty"`
	LableId1             string               `protobuf:"bytes,4,opt,name=lable_id1,json=lableId1,proto3" json:"lable_id1,omitempty"`
	LableName1           string               `protobuf:"bytes,5,opt,name=lable_name1,json=lableName1,proto3" json:"lable_name1,omitempty"`
	LableId2             string               `protobuf:"bytes,6,opt,name=lable_id2,json=lableId2,proto3" json:"lable_id2,omitempty"`
	LableName2           string               `protobuf:"bytes,7,opt,name=lable_name2,json=lableName2,proto3" json:"lable_name2,omitempty"`
	LableId3             string               `protobuf:"bytes,8,opt,name=lable_id3,json=lableId3,proto3" json:"lable_id3,omitempty"`
	LableName3           string               `protobuf:"bytes,9,opt,name=lable_name3,json=lableName3,proto3" json:"lable_name3,omitempty"`
	LableId4             string               `protobuf:"bytes,10,opt,name=lable_id4,json=lableId4,proto3" json:"lable_id4,omitempty"`
	LableName4           string               `protobuf:"bytes,11,opt,name=lable_name4,json=lableName4,proto3" json:"lable_name4,omitempty"`
	RegisterDate         *timestamp.Timestamp `protobuf:"bytes,12,opt,name=register_date,json=registerDate,proto3" json:"register_date,omitempty"`
	CreateDate           *timestamp.Timestamp `protobuf:"bytes,13,opt,name=create_date,json=createDate,proto3" json:"create_date,omitempty"`
	PartitionId          string               `protobuf:"bytes,14,opt,name=partition_id,json=partitionId,proto3" json:"partition_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *TUserPortrait) Reset()         { *m = TUserPortrait{} }
func (m *TUserPortrait) String() string { return proto.CompactTextString(m) }
func (*TUserPortrait) ProtoMessage()    {}
func (*TUserPortrait) Descriptor() ([]byte, []int) {
	return fileDescriptor_t_userportrait_fec5dbb9549dbc00, []int{0}
}
func (m *TUserPortrait) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TUserPortrait.Unmarshal(m, b)
}
func (m *TUserPortrait) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TUserPortrait.Marshal(b, m, deterministic)
}
func (dst *TUserPortrait) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TUserPortrait.Merge(dst, src)
}
func (m *TUserPortrait) XXX_Size() int {
	return xxx_messageInfo_TUserPortrait.Size(m)
}
func (m *TUserPortrait) XXX_DiscardUnknown() {
	xxx_messageInfo_TUserPortrait.DiscardUnknown(m)
}

var xxx_messageInfo_TUserPortrait proto.InternalMessageInfo

func (m *TUserPortrait) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *TUserPortrait) GetMobile() string {
	if m != nil {
		return m.Mobile
	}
	return ""
}

func (m *TUserPortrait) GetNikeName() string {
	if m != nil {
		return m.NikeName
	}
	return ""
}

func (m *TUserPortrait) GetLableId1() string {
	if m != nil {
		return m.LableId1
	}
	return ""
}

func (m *TUserPortrait) GetLableName1() string {
	if m != nil {
		return m.LableName1
	}
	return ""
}

func (m *TUserPortrait) GetLableId2() string {
	if m != nil {
		return m.LableId2
	}
	return ""
}

func (m *TUserPortrait) GetLableName2() string {
	if m != nil {
		return m.LableName2
	}
	return ""
}

func (m *TUserPortrait) GetLableId3() string {
	if m != nil {
		return m.LableId3
	}
	return ""
}

func (m *TUserPortrait) GetLableName3() string {
	if m != nil {
		return m.LableName3
	}
	return ""
}

func (m *TUserPortrait) GetLableId4() string {
	if m != nil {
		return m.LableId4
	}
	return ""
}

func (m *TUserPortrait) GetLableName4() string {
	if m != nil {
		return m.LableName4
	}
	return ""
}

func (m *TUserPortrait) GetRegisterDate() *timestamp.Timestamp {
	if m != nil {
		return m.RegisterDate
	}
	return nil
}

func (m *TUserPortrait) GetCreateDate() *timestamp.Timestamp {
	if m != nil {
		return m.CreateDate
	}
	return nil
}

func (m *TUserPortrait) GetPartitionId() string {
	if m != nil {
		return m.PartitionId
	}
	return ""
}

func init() {
	proto.RegisterType((*TUserPortrait)(nil), "usercenter.TUserPortrait")
}

func init() {
	proto.RegisterFile("usercenter/t_userportrait.proto", fileDescriptor_t_userportrait_fec5dbb9549dbc00)
}

var fileDescriptor_t_userportrait_fec5dbb9549dbc00 = []byte{
	// 335 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0xd1, 0xbf, 0x4f, 0xc2, 0x40,
	0x14, 0x07, 0xf0, 0x00, 0x5a, 0xe1, 0x0a, 0x0c, 0x1d, 0xcc, 0x0b, 0x0e, 0xa0, 0x13, 0x53, 0x9b,
	0xfe, 0xd8, 0x18, 0x4c, 0x8c, 0x0b, 0x8b, 0x31, 0x04, 0x17, 0x97, 0xe6, 0xca, 0x3d, 0xeb, 0xc5,
	0x5e, 0xaf, 0xb9, 0x3e, 0x06, 0xff, 0x68, 0xff, 0x07, 0xd3, 0x2b, 0x08, 0x65, 0x71, 0xeb, 0x7d,
	0xbf, 0xef, 0x73, 0xbd, 0xe4, 0xb1, 0xf9, 0xbe, 0x46, 0xb3, 0xc3, 0x92, 0xd0, 0x04, 0x94, 0x36,
	0x87, 0x4a, 0x1b, 0x32, 0x5c, 0x92, 0x5f, 0x19, 0x4d, 0xda, 0x63, 0xa7, 0x81, 0xd9, 0x2a, 0x97,
	0xf4, 0xb9, 0xcf, 0xfc, 0x9d, 0x56, 0x41, 0xae, 0x0b, 0x5e, 0xe6, 0x81, 0x1d, 0xca, 0xf6, 0x1f,
	0x41, 0x45, 0xdf, 0x15, 0xd6, 0x01, 0x49, 0x85, 0x35, 0x71, 0x55, 0x9d, 0xbe, 0xda, 0x8b, 0x1e,
	0x7e, 0x06, 0x6c, 0xb2, 0x7d, 0xab, 0xd1, 0xbc, 0x1e, 0x7e, 0xe0, 0x4d, 0x59, 0x5f, 0x0a, 0xe8,
	0x2d, 0x7a, 0xcb, 0xd1, 0xa6, 0x2f, 0x85, 0x77, 0xcb, 0x1c, 0xa5, 0x33, 0x59, 0x20, 0xf4, 0x6d,
	0x76, 0x38, 0x79, 0x77, 0x6c, 0x54, 0xca, 0x2f, 0x4c, 0x4b, 0xae, 0x10, 0x06, 0xb6, 0x1a, 0x36,
	0xc1, 0x0b, 0x57, 0xb6, 0x2c, 0x78, 0x56, 0x60, 0x2a, 0x45, 0x08, 0x57, 0x6d, 0x69, 0x83, 0xb5,
	0x08, 0xbd, 0x39, 0x73, 0xdb, 0xb2, 0xa1, 0x21, 0x5c, 0xdb, 0x9a, 0xd9, 0xa8, 0xc1, 0xe1, 0xb9,
	0x8e, 0xc0, 0xe9, 0xe8, 0xa8, 0xab, 0x23, 0xb8, 0xb9, 0xd0, 0xd1, 0xb9, 0x8e, 0x61, 0xd8, 0xd1,
	0x71, 0x57, 0xc7, 0x30, 0xba, 0xd0, 0xf1, 0xb9, 0x4e, 0x80, 0x75, 0x74, 0xd2, 0xd5, 0x09, 0xb8,
	0x17, 0x3a, 0xf1, 0x1e, 0xd9, 0xc4, 0x60, 0x2e, 0x6b, 0x42, 0x93, 0x0a, 0x4e, 0x08, 0xe3, 0x45,
	0x6f, 0xe9, 0x46, 0x33, 0x3f, 0xd7, 0x3a, 0x2f, 0xd0, 0x3f, 0x2e, 0xc6, 0xdf, 0x1e, 0xf7, 0xb0,
	0x19, 0x1f, 0xc1, 0x33, 0x27, 0xf4, 0x56, 0xcc, 0xdd, 0x19, 0xe4, 0x84, 0x2d, 0x9f, 0xfc, 0xcb,
	0x59, 0x3b, 0x6e, 0xf1, 0x3d, 0x1b, 0x57, 0xdc, 0x90, 0x24, 0xa9, 0xcb, 0x54, 0x0a, 0x98, 0xda,
	0xf7, 0xb9, 0x7f, 0xd9, 0x5a, 0x3c, 0x0d, 0xdf, 0x1d, 0xa5, 0x05, 0x16, 0x75, 0xe6, 0xd8, 0xcb,
	0xe2, 0xdf, 0x00, 0x00, 0x00, 0xff, 0xff, 0xab, 0xc7, 0x41, 0x44, 0x6c, 0x02, 0x00, 0x00,
}
