// Code generated by protoc-gen-go. DO NOT EDIT.
// source: usercenter/t_brand.proto

package models

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "github.com/golang/protobuf/ptypes/timestamp"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type TBrand struct {
	Msisdn               string   `protobuf:"bytes,1,opt,name=msisdn,proto3" json:"msisdn,omitempty"`
	Deviceid             string   `protobuf:"bytes,2,opt,name=deviceid,proto3" json:"deviceid,omitempty"`
	Brand                string   `protobuf:"bytes,3,opt,name=brand,proto3" json:"brand,omitempty"`
	District             string   `protobuf:"bytes,4,opt,name=district,proto3" json:"district,omitempty"`
	Music                string   `protobuf:"bytes,5,opt,name=music,proto3" json:"music,omitempty"`
	Read                 string   `protobuf:"bytes,6,opt,name=read,proto3" json:"read,omitempty"`
	News                 string   `protobuf:"bytes,7,opt,name=news,proto3" json:"news,omitempty"`
	Weather              string   `protobuf:"bytes,8,opt,name=weather,proto3" json:"weather,omitempty"`
	Video                string   `protobuf:"bytes,9,opt,name=video,proto3" json:"video,omitempty"`
	App                  string   `protobuf:"bytes,10,opt,name=app,proto3" json:"app,omitempty"`
	Email                string   `protobuf:"bytes,11,opt,name=email,proto3" json:"email,omitempty"`
	Sns                  string   `protobuf:"bytes,12,opt,name=sns,proto3" json:"sns,omitempty"`
	Foreign              string   `protobuf:"bytes,13,opt,name=foreign,proto3" json:"foreign,omitempty"`
	Student              string   `protobuf:"bytes,14,opt,name=student,proto3" json:"student,omitempty"`
	Business             string   `protobuf:"bytes,15,opt,name=business,proto3" json:"business,omitempty"`
	Partitionid          string   `protobuf:"bytes,16,opt,name=partitionid,proto3" json:"partitionid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TBrand) Reset()         { *m = TBrand{} }
func (m *TBrand) String() string { return proto.CompactTextString(m) }
func (*TBrand) ProtoMessage()    {}
func (*TBrand) Descriptor() ([]byte, []int) {
	return fileDescriptor_t_brand_9faf0b7dfdb6af29, []int{0}
}
func (m *TBrand) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TBrand.Unmarshal(m, b)
}
func (m *TBrand) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TBrand.Marshal(b, m, deterministic)
}
func (dst *TBrand) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TBrand.Merge(dst, src)
}
func (m *TBrand) XXX_Size() int {
	return xxx_messageInfo_TBrand.Size(m)
}
func (m *TBrand) XXX_DiscardUnknown() {
	xxx_messageInfo_TBrand.DiscardUnknown(m)
}

var xxx_messageInfo_TBrand proto.InternalMessageInfo

func (m *TBrand) GetMsisdn() string {
	if m != nil {
		return m.Msisdn
	}
	return ""
}

func (m *TBrand) GetDeviceid() string {
	if m != nil {
		return m.Deviceid
	}
	return ""
}

func (m *TBrand) GetBrand() string {
	if m != nil {
		return m.Brand
	}
	return ""
}

func (m *TBrand) GetDistrict() string {
	if m != nil {
		return m.District
	}
	return ""
}

func (m *TBrand) GetMusic() string {
	if m != nil {
		return m.Music
	}
	return ""
}

func (m *TBrand) GetRead() string {
	if m != nil {
		return m.Read
	}
	return ""
}

func (m *TBrand) GetNews() string {
	if m != nil {
		return m.News
	}
	return ""
}

func (m *TBrand) GetWeather() string {
	if m != nil {
		return m.Weather
	}
	return ""
}

func (m *TBrand) GetVideo() string {
	if m != nil {
		return m.Video
	}
	return ""
}

func (m *TBrand) GetApp() string {
	if m != nil {
		return m.App
	}
	return ""
}

func (m *TBrand) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *TBrand) GetSns() string {
	if m != nil {
		return m.Sns
	}
	return ""
}

func (m *TBrand) GetForeign() string {
	if m != nil {
		return m.Foreign
	}
	return ""
}

func (m *TBrand) GetStudent() string {
	if m != nil {
		return m.Student
	}
	return ""
}

func (m *TBrand) GetBusiness() string {
	if m != nil {
		return m.Business
	}
	return ""
}

func (m *TBrand) GetPartitionid() string {
	if m != nil {
		return m.Partitionid
	}
	return ""
}

func init() {
	proto.RegisterType((*TBrand)(nil), "usercenter.TBrand")
}

func init() { proto.RegisterFile("usercenter/t_brand.proto", fileDescriptor_t_brand_9faf0b7dfdb6af29) }

var fileDescriptor_t_brand_9faf0b7dfdb6af29 = []byte{
	// 311 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x91, 0x3f, 0x6f, 0xc2, 0x30,
	0x10, 0xc5, 0x45, 0x81, 0x00, 0xa6, 0x7f, 0x90, 0x55, 0x55, 0x27, 0x26, 0xd4, 0xa9, 0x13, 0x19,
	0x3a, 0x76, 0xe3, 0x23, 0x54, 0x9d, 0xba, 0x54, 0x4e, 0x7c, 0x84, 0x93, 0x88, 0x1d, 0xf9, 0x1c,
	0x50, 0xbf, 0x41, 0x3f, 0x76, 0xe5, 0x73, 0x28, 0xdd, 0xee, 0xf7, 0xde, 0xbb, 0xe7, 0x9c, 0xa2,
	0xa0, 0x67, 0x0c, 0x35, 0xba, 0x88, 0xa1, 0x8c, 0x5f, 0x55, 0x30, 0xce, 0x6e, 0xbb, 0xe0, 0xa3,
	0xd7, 0xea, 0xea, 0xac, 0xdf, 0x1a, 0x8a, 0x87, 0xbe, 0xda, 0xd6, 0xbe, 0x2d, 0x1b, 0x7f, 0x34,
	0xae, 0x29, 0x25, 0x54, 0xf5, 0xfb, 0xb2, 0x8b, 0xdf, 0x1d, 0x72, 0x19, 0xa9, 0x45, 0x8e, 0xa6,
	0xed, 0xae, 0x53, 0x2e, 0x7a, 0xfe, 0x19, 0xab, 0xe2, 0x63, 0x97, 0x9a, 0xf5, 0x93, 0x2a, 0x5a,
	0x26, 0xb6, 0x0e, 0x46, 0x9b, 0xd1, 0xcb, 0xe2, 0x7d, 0x20, 0xbd, 0x56, 0x73, 0x8b, 0x27, 0xaa,
	0x91, 0x2c, 0xdc, 0x88, 0xf3, 0xc7, 0xfa, 0x51, 0x4d, 0xe5, 0xb3, 0x60, 0x2c, 0x46, 0x06, 0xd9,
	0x20, 0x8e, 0x81, 0xea, 0x08, 0x93, 0x61, 0x63, 0xe0, 0xb4, 0xd1, 0xf6, 0x4c, 0x35, 0x4c, 0xf3,
	0x86, 0x80, 0xd6, 0x6a, 0x12, 0xd0, 0x58, 0x28, 0x44, 0x94, 0x39, 0x69, 0x0e, 0xcf, 0x0c, 0xb3,
	0xac, 0xa5, 0x59, 0x83, 0x9a, 0x9d, 0xd1, 0xc4, 0x03, 0x06, 0x98, 0x8b, 0x7c, 0xc1, 0xd4, 0x7b,
	0x22, 0x8b, 0x1e, 0x16, 0xb9, 0x57, 0x40, 0xaf, 0xd4, 0xd8, 0x74, 0x1d, 0x28, 0xd1, 0xd2, 0x98,
	0x72, 0xd8, 0x1a, 0x3a, 0xc2, 0x32, 0xe7, 0x04, 0x52, 0x8e, 0x1d, 0xc3, 0x6d, 0xce, 0xb1, 0x93,
	0x97, 0xf6, 0x3e, 0x20, 0x35, 0x0e, 0xee, 0xf2, 0x4b, 0x03, 0x26, 0x87, 0x63, 0x6f, 0xd1, 0x45,
	0xb8, 0xcf, 0xce, 0x80, 0xe9, 0xee, 0xaa, 0x67, 0x72, 0xc8, 0x0c, 0x0f, 0xf9, 0xee, 0x0b, 0xeb,
	0x8d, 0x5a, 0x76, 0x26, 0x44, 0x8a, 0xe4, 0x1d, 0x59, 0x58, 0x89, 0xfd, 0x5f, 0xda, 0xcd, 0x3f,
	0x8b, 0xd6, 0x5b, 0x3c, 0x72, 0x55, 0xc8, 0xbf, 0x79, 0xfd, 0x0d, 0x00, 0x00, 0xff, 0xff, 0x46,
	0xba, 0x2b, 0x0b, 0x00, 0x02, 0x00, 0x00,
}
