// Code generated by protoc-gen-go. DO NOT EDIT.
// source: usercenter/t_exchangegoodslimit.proto

package models

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import timestamp "github.com/golang/protobuf/ptypes/timestamp"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type TExchangeGoodsLimit struct {
	GoodsId              string               `protobuf:"bytes,1,opt,name=goods_id,json=goodsId,proto3" json:"goods_id,omitempty"`
	Channel              string               `protobuf:"bytes,2,opt,name=channel,proto3" json:"channel,omitempty"`
	ShowStatus           string               `protobuf:"bytes,3,opt,name=show_status,json=showStatus,proto3" json:"show_status,omitempty"`
	TotalNum             string               `protobuf:"bytes,4,opt,name=total_num,json=totalNum,proto3" json:"total_num,omitempty"`
	CurrentNum           string               `protobuf:"bytes,5,opt,name=current_num,json=currentNum,proto3" json:"current_num,omitempty"`
	ExchangeNum          string               `protobuf:"bytes,6,opt,name=exchange_num,json=exchangeNum,proto3" json:"exchange_num,omitempty"`
	EqualMcoin           string               `protobuf:"bytes,7,opt,name=equal_mcoin,json=equalMcoin,proto3" json:"equal_mcoin,omitempty"`
	EqualScore           string               `protobuf:"bytes,8,opt,name=equal_score,json=equalScore,proto3" json:"equal_score,omitempty"`
	DayLimit             string               `protobuf:"bytes,9,opt,name=day_limit,json=dayLimit,proto3" json:"day_limit,omitempty"`
	PersonLimit          string               `protobuf:"bytes,10,opt,name=person_limit,json=personLimit,proto3" json:"person_limit,omitempty"`
	DayCurrentNum        string               `protobuf:"bytes,11,opt,name=day_current_num,json=dayCurrentNum,proto3" json:"day_current_num,omitempty"`
	MemberGrade          string               `protobuf:"bytes,12,opt,name=member_grade,json=memberGrade,proto3" json:"member_grade,omitempty"`
	Sort                 string               `protobuf:"bytes,13,opt,name=sort,proto3" json:"sort,omitempty"`
	CreateDate           *timestamp.Timestamp `protobuf:"bytes,14,opt,name=create_date,json=createDate,proto3" json:"create_date,omitempty"`
	OperateDate          *timestamp.Timestamp `protobuf:"bytes,15,opt,name=operate_date,json=operateDate,proto3" json:"operate_date,omitempty"`
	WarnThreshold        string               `protobuf:"bytes,16,opt,name=warn_threshold,json=warnThreshold,proto3" json:"warn_threshold,omitempty"`
	UnionPrice           string               `protobuf:"bytes,17,opt,name=union_price,json=unionPrice,proto3" json:"union_price,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *TExchangeGoodsLimit) Reset()         { *m = TExchangeGoodsLimit{} }
func (m *TExchangeGoodsLimit) String() string { return proto.CompactTextString(m) }
func (*TExchangeGoodsLimit) ProtoMessage()    {}
func (*TExchangeGoodsLimit) Descriptor() ([]byte, []int) {
	return fileDescriptor_t_exchangegoodslimit_3ddc9b14be6f5cb8, []int{0}
}
func (m *TExchangeGoodsLimit) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TExchangeGoodsLimit.Unmarshal(m, b)
}
func (m *TExchangeGoodsLimit) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TExchangeGoodsLimit.Marshal(b, m, deterministic)
}
func (dst *TExchangeGoodsLimit) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TExchangeGoodsLimit.Merge(dst, src)
}
func (m *TExchangeGoodsLimit) XXX_Size() int {
	return xxx_messageInfo_TExchangeGoodsLimit.Size(m)
}
func (m *TExchangeGoodsLimit) XXX_DiscardUnknown() {
	xxx_messageInfo_TExchangeGoodsLimit.DiscardUnknown(m)
}

var xxx_messageInfo_TExchangeGoodsLimit proto.InternalMessageInfo

func (m *TExchangeGoodsLimit) GetGoodsId() string {
	if m != nil {
		return m.GoodsId
	}
	return ""
}

func (m *TExchangeGoodsLimit) GetChannel() string {
	if m != nil {
		return m.Channel
	}
	return ""
}

func (m *TExchangeGoodsLimit) GetShowStatus() string {
	if m != nil {
		return m.ShowStatus
	}
	return ""
}

func (m *TExchangeGoodsLimit) GetTotalNum() string {
	if m != nil {
		return m.TotalNum
	}
	return ""
}

func (m *TExchangeGoodsLimit) GetCurrentNum() string {
	if m != nil {
		return m.CurrentNum
	}
	return ""
}

func (m *TExchangeGoodsLimit) GetExchangeNum() string {
	if m != nil {
		return m.ExchangeNum
	}
	return ""
}

func (m *TExchangeGoodsLimit) GetEqualMcoin() string {
	if m != nil {
		return m.EqualMcoin
	}
	return ""
}

func (m *TExchangeGoodsLimit) GetEqualScore() string {
	if m != nil {
		return m.EqualScore
	}
	return ""
}

func (m *TExchangeGoodsLimit) GetDayLimit() string {
	if m != nil {
		return m.DayLimit
	}
	return ""
}

func (m *TExchangeGoodsLimit) GetPersonLimit() string {
	if m != nil {
		return m.PersonLimit
	}
	return ""
}

func (m *TExchangeGoodsLimit) GetDayCurrentNum() string {
	if m != nil {
		return m.DayCurrentNum
	}
	return ""
}

func (m *TExchangeGoodsLimit) GetMemberGrade() string {
	if m != nil {
		return m.MemberGrade
	}
	return ""
}

func (m *TExchangeGoodsLimit) GetSort() string {
	if m != nil {
		return m.Sort
	}
	return ""
}

func (m *TExchangeGoodsLimit) GetCreateDate() *timestamp.Timestamp {
	if m != nil {
		return m.CreateDate
	}
	return nil
}

func (m *TExchangeGoodsLimit) GetOperateDate() *timestamp.Timestamp {
	if m != nil {
		return m.OperateDate
	}
	return nil
}

func (m *TExchangeGoodsLimit) GetWarnThreshold() string {
	if m != nil {
		return m.WarnThreshold
	}
	return ""
}

func (m *TExchangeGoodsLimit) GetUnionPrice() string {
	if m != nil {
		return m.UnionPrice
	}
	return ""
}

func init() {
	proto.RegisterType((*TExchangeGoodsLimit)(nil), "usercenter.TExchangeGoodsLimit")
}

func init() {
	proto.RegisterFile("usercenter/t_exchangegoodslimit.proto", fileDescriptor_t_exchangegoodslimit_3ddc9b14be6f5cb8)
}

var fileDescriptor_t_exchangegoodslimit_3ddc9b14be6f5cb8 = []byte{
	// 435 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x91, 0xcd, 0x6e, 0xd4, 0x30,
	0x10, 0x80, 0xb5, 0xb0, 0xec, 0x8f, 0xb3, 0x6d, 0x21, 0x5c, 0x4c, 0x39, 0xd0, 0x22, 0x15, 0xf5,
	0x94, 0x48, 0x70, 0xac, 0xb8, 0xf0, 0xa3, 0x0a, 0x09, 0x10, 0x6a, 0xf7, 0xc4, 0xc5, 0xf2, 0xc6,
	0x43, 0x12, 0x29, 0xf6, 0x04, 0x7b, 0xa2, 0xb2, 0x8f, 0xcd, 0x1b, 0x20, 0x8f, 0x13, 0xb6, 0x9c,
	0xb8, 0xd9, 0xdf, 0x7c, 0x33, 0xe3, 0x19, 0x8b, 0x8b, 0x21, 0x80, 0xaf, 0xc0, 0x11, 0xf8, 0x92,
	0x14, 0xfc, 0xaa, 0x1a, 0xed, 0x6a, 0xa8, 0x11, 0x4d, 0xe8, 0x5a, 0xdb, 0x52, 0xd1, 0x7b, 0x24,
	0xcc, 0xc5, 0x41, 0x3b, 0xbd, 0xaa, 0x5b, 0x6a, 0x86, 0x5d, 0x51, 0xa1, 0x2d, 0x6b, 0xec, 0xb4,
	0xab, 0x4b, 0x96, 0x76, 0xc3, 0x8f, 0xb2, 0xa7, 0x7d, 0x0f, 0xa1, 0xa4, 0xd6, 0x42, 0x20, 0x6d,
	0xfb, 0xc3, 0x29, 0x15, 0x7a, 0xf9, 0x7b, 0x2e, 0x9e, 0x6e, 0x3f, 0x8e, 0x6d, 0xae, 0x63, 0x9b,
	0xcf, 0xb1, 0x4d, 0xfe, 0x4c, 0xac, 0xb8, 0xa9, 0x6a, 0x8d, 0x9c, 0x9d, 0xcd, 0x2e, 0xd7, 0x37,
	0x4b, 0xbe, 0x7f, 0x32, 0xb9, 0x14, 0xcb, 0xa8, 0x3b, 0xe8, 0xe4, 0x83, 0x14, 0x19, 0xaf, 0xf9,
	0x0b, 0x91, 0x85, 0x06, 0xef, 0x54, 0x20, 0x4d, 0x43, 0x90, 0x0f, 0x39, 0x2a, 0x22, 0xba, 0x65,
	0x92, 0x3f, 0x17, 0x6b, 0x42, 0xd2, 0x9d, 0x72, 0x83, 0x95, 0x73, 0x0e, 0xaf, 0x18, 0x7c, 0x1d,
	0x6c, 0xcc, 0xae, 0x06, 0xef, 0xc1, 0x11, 0x87, 0x1f, 0xa5, 0xec, 0x11, 0x45, 0xe1, 0x5c, 0x6c,
	0xa6, 0x85, 0xb0, 0xb1, 0x60, 0x23, 0x9b, 0xd8, 0x58, 0x03, 0x7e, 0x0e, 0xba, 0x53, 0xb6, 0xc2,
	0xd6, 0xc9, 0x65, 0xaa, 0xc1, 0xe8, 0x4b, 0x24, 0x07, 0x21, 0x54, 0xe8, 0x41, 0xae, 0xee, 0x09,
	0xb7, 0x91, 0xc4, 0x27, 0x1a, 0xbd, 0x57, 0xbc, 0x6c, 0xb9, 0x4e, 0x4f, 0x34, 0x7a, 0x9f, 0xb6,
	0x72, 0x2e, 0x36, 0x3d, 0xf8, 0x80, 0x6e, 0x8c, 0x8b, 0xf4, 0x82, 0xc4, 0x92, 0xf2, 0x4a, 0x9c,
	0xc4, 0xfc, 0xfb, 0x93, 0x64, 0x6c, 0x1d, 0x19, 0xbd, 0x7f, 0xff, 0xcf, 0x30, 0x16, 0xec, 0x0e,
	0xbc, 0xaa, 0xbd, 0x36, 0x20, 0x37, 0xa9, 0x54, 0x62, 0xd7, 0x11, 0xe5, 0xb9, 0x98, 0x07, 0xf4,
	0x24, 0x8f, 0x38, 0xc4, 0xe7, 0xfc, 0x4a, 0x64, 0x95, 0x07, 0x4d, 0xa0, 0x8c, 0x26, 0x90, 0xc7,
	0x67, 0xb3, 0xcb, 0xec, 0xf5, 0x69, 0x51, 0x23, 0xd6, 0x1d, 0x14, 0xd3, 0xbf, 0x17, 0xdb, 0xe9,
	0x9b, 0x6f, 0x44, 0xd2, 0x3f, 0x68, 0x82, 0xfc, 0xad, 0xd8, 0x60, 0x0f, 0xfe, 0x6f, 0xf6, 0xc9,
	0x7f, 0xb3, 0xb3, 0xd1, 0xe7, 0xf4, 0x0b, 0x71, 0x7c, 0xa7, 0xbd, 0x53, 0xd4, 0x78, 0x08, 0x0d,
	0x76, 0x46, 0x3e, 0x4e, 0x93, 0x45, 0xba, 0x9d, 0x60, 0x5c, 0xf1, 0xe0, 0x5a, 0x74, 0xaa, 0xf7,
	0x6d, 0x05, 0xf2, 0x49, 0x5a, 0x31, 0xa3, 0x6f, 0x91, 0xbc, 0x5b, 0x7d, 0x5f, 0x58, 0x34, 0xd0,
	0x85, 0xdd, 0x82, 0x5b, 0xbe, 0xf9, 0x13, 0x00, 0x00, 0xff, 0xff, 0x44, 0x1f, 0xc2, 0xc4, 0xf6,
	0x02, 0x00, 0x00,
}
