// Code generated by protoc-gen-go. DO NOT EDIT.
// source: usercenter/t_goldconfig.proto

package models

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "github.com/golang/protobuf/ptypes/timestamp"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type TGoldConfig struct {
	Circle               string   `protobuf:"bytes,1,opt,name=circle,proto3" json:"circle,omitempty"`
	LimitCount           string   `protobuf:"bytes,2,opt,name=limit_count,json=limitCount,proto3" json:"limit_count,omitempty"`
	Descs                string   `protobuf:"bytes,3,opt,name=descs,proto3" json:"descs,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TGoldConfig) Reset()         { *m = TGoldConfig{} }
func (m *TGoldConfig) String() string { return proto.CompactTextString(m) }
func (*TGoldConfig) ProtoMessage()    {}
func (*TGoldConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_t_goldconfig_25728fb9a8a6d73d, []int{0}
}
func (m *TGoldConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TGoldConfig.Unmarshal(m, b)
}
func (m *TGoldConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TGoldConfig.Marshal(b, m, deterministic)
}
func (dst *TGoldConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TGoldConfig.Merge(dst, src)
}
func (m *TGoldConfig) XXX_Size() int {
	return xxx_messageInfo_TGoldConfig.Size(m)
}
func (m *TGoldConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_TGoldConfig.DiscardUnknown(m)
}

var xxx_messageInfo_TGoldConfig proto.InternalMessageInfo

func (m *TGoldConfig) GetCircle() string {
	if m != nil {
		return m.Circle
	}
	return ""
}

func (m *TGoldConfig) GetLimitCount() string {
	if m != nil {
		return m.LimitCount
	}
	return ""
}

func (m *TGoldConfig) GetDescs() string {
	if m != nil {
		return m.Descs
	}
	return ""
}

func init() {
	proto.RegisterType((*TGoldConfig)(nil), "usercenter.TGoldConfig")
}

func init() {
	proto.RegisterFile("usercenter/t_goldconfig.proto", fileDescriptor_t_goldconfig_25728fb9a8a6d73d)
}

var fileDescriptor_t_goldconfig_25728fb9a8a6d73d = []byte{
	// 187 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x44, 0x8d, 0x31, 0x6b, 0xc3, 0x30,
	0x10, 0x85, 0x71, 0x4b, 0x4d, 0x2b, 0x6f, 0xa2, 0x14, 0x53, 0x28, 0x2d, 0x9d, 0x32, 0x59, 0x43,
	0xc6, 0x6c, 0xf1, 0x90, 0x3d, 0x64, 0x0a, 0x01, 0x63, 0x4b, 0x67, 0x45, 0x20, 0xe9, 0x84, 0x74,
	0x1a, 0xf2, 0xef, 0x43, 0xe4, 0x80, 0xb7, 0x7b, 0xef, 0x3b, 0xbe, 0xc7, 0x7e, 0x72, 0x82, 0x28,
	0xc1, 0x13, 0x44, 0x41, 0x83, 0x46, 0xab, 0x24, 0xfa, 0xd9, 0xe8, 0x2e, 0x44, 0x24, 0xe4, 0x6c,
	0xc5, 0xdf, 0x3b, 0x6d, 0xe8, 0x9a, 0xa7, 0x4e, 0xa2, 0x13, 0x1a, 0xed, 0xe8, 0xb5, 0x28, 0x4f,
	0x53, 0x9e, 0x45, 0xa0, 0x5b, 0x80, 0x24, 0xc8, 0x38, 0x48, 0x34, 0xba, 0xb0, 0x5e, 0x8b, 0xe8,
	0xff, 0xc2, 0x9a, 0xd3, 0x01, 0xad, 0xea, 0x8b, 0x9d, 0x7f, 0xb1, 0x5a, 0x9a, 0x28, 0x2d, 0xb4,
	0xd5, 0x5f, 0xb5, 0xf9, 0x38, 0x3e, 0x13, 0xff, 0x65, 0x8d, 0x35, 0xce, 0xd0, 0x20, 0x31, 0x7b,
	0x6a, 0x5f, 0x0a, 0x64, 0xa5, 0xea, 0x1f, 0x0d, 0xff, 0x64, 0x6f, 0x0a, 0x92, 0x4c, 0xed, 0x6b,
	0x41, 0x4b, 0xd8, 0xbf, 0x9f, 0x6b, 0x87, 0x0a, 0x6c, 0x9a, 0xea, 0x32, 0xb7, 0xbd, 0x07, 0x00,
	0x00, 0xff, 0xff, 0x47, 0x19, 0xd4, 0xe3, 0xd8, 0x00, 0x00, 0x00,
}
