// Code generated by protoc-gen-go. DO NOT EDIT.
// source: usercenter/t_mcoinusedetail.proto

package models

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "github.com/golang/protobuf/ptypes/timestamp"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type TMcoinusedetail struct {
	Seq                  string   `protobuf:"bytes,1,opt,name=seq,proto3" json:"seq,omitempty"`
	Getseq               string   `protobuf:"bytes,2,opt,name=getseq,proto3" json:"getseq,omitempty"`
	Useseq               string   `protobuf:"bytes,3,opt,name=useseq,proto3" json:"useseq,omitempty"`
	Value                string   `protobuf:"bytes,4,opt,name=value,proto3" json:"value,omitempty"`
	Mcoin                string   `protobuf:"bytes,5,opt,name=mcoin,proto3" json:"mcoin,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TMcoinusedetail) Reset()         { *m = TMcoinusedetail{} }
func (m *TMcoinusedetail) String() string { return proto.CompactTextString(m) }
func (*TMcoinusedetail) ProtoMessage()    {}
func (*TMcoinusedetail) Descriptor() ([]byte, []int) {
	return fileDescriptor_t_mcoinusedetail_44b18d67b798c8e3, []int{0}
}
func (m *TMcoinusedetail) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TMcoinusedetail.Unmarshal(m, b)
}
func (m *TMcoinusedetail) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TMcoinusedetail.Marshal(b, m, deterministic)
}
func (dst *TMcoinusedetail) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TMcoinusedetail.Merge(dst, src)
}
func (m *TMcoinusedetail) XXX_Size() int {
	return xxx_messageInfo_TMcoinusedetail.Size(m)
}
func (m *TMcoinusedetail) XXX_DiscardUnknown() {
	xxx_messageInfo_TMcoinusedetail.DiscardUnknown(m)
}

var xxx_messageInfo_TMcoinusedetail proto.InternalMessageInfo

func (m *TMcoinusedetail) GetSeq() string {
	if m != nil {
		return m.Seq
	}
	return ""
}

func (m *TMcoinusedetail) GetGetseq() string {
	if m != nil {
		return m.Getseq
	}
	return ""
}

func (m *TMcoinusedetail) GetUseseq() string {
	if m != nil {
		return m.Useseq
	}
	return ""
}

func (m *TMcoinusedetail) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func (m *TMcoinusedetail) GetMcoin() string {
	if m != nil {
		return m.Mcoin
	}
	return ""
}

func init() {
	proto.RegisterType((*TMcoinusedetail)(nil), "usercenter.TMcoinusedetail")
}

func init() {
	proto.RegisterFile("usercenter/t_mcoinusedetail.proto", fileDescriptor_t_mcoinusedetail_44b18d67b798c8e3)
}

var fileDescriptor_t_mcoinusedetail_44b18d67b798c8e3 = []byte{
	// 194 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0xcf, 0xbf, 0x8b, 0xc2, 0x30,
	0x14, 0xc0, 0x71, 0x7a, 0xbd, 0x96, 0xbb, 0x2c, 0x4a, 0x10, 0x29, 0x4e, 0xea, 0xe4, 0xd4, 0x0c,
	0x8e, 0x6e, 0xee, 0x2e, 0xe2, 0xe4, 0x22, 0x69, 0xfb, 0x8c, 0x81, 0xa4, 0x89, 0xcd, 0x8b, 0xe0,
	0xe4, 0xbf, 0x2e, 0x49, 0x84, 0xe2, 0xf6, 0xbe, 0x1f, 0x1e, 0xf9, 0x41, 0x56, 0xde, 0xc1, 0xd0,
	0x42, 0x8f, 0x30, 0x30, 0xbc, 0xe8, 0xd6, 0xc8, 0xde, 0x3b, 0xe8, 0x00, 0xb9, 0x54, 0xb5, 0x1d,
	0x0c, 0x1a, 0x4a, 0xc6, 0x95, 0xc5, 0x4e, 0x48, 0xbc, 0xf9, 0xa6, 0x6e, 0x8d, 0x66, 0xc2, 0x28,
	0xde, 0x0b, 0x16, 0x97, 0x1a, 0x7f, 0x65, 0x16, 0x9f, 0x16, 0x1c, 0x43, 0xa9, 0xc1, 0x21, 0xd7,
	0x76, 0x9c, 0xd2, 0x41, 0xeb, 0x17, 0x99, 0x9c, 0x0e, 0x5f, 0x37, 0xd0, 0x29, 0xc9, 0x1d, 0xdc,
	0xab, 0x6c, 0x99, 0x6d, 0xfe, 0x8f, 0x61, 0xa4, 0x73, 0x52, 0x0a, 0xc0, 0x80, 0x3f, 0x11, 0x3f,
	0x15, 0xdc, 0x3b, 0x08, 0x9e, 0x27, 0x4f, 0x45, 0x67, 0xa4, 0x78, 0x70, 0xe5, 0xa1, 0xfa, 0x8d,
	0x9c, 0x22, 0x68, 0xfc, 0x4b, 0x55, 0x24, 0x8d, 0xb1, 0xff, 0x3b, 0x97, 0xda, 0x74, 0xa0, 0x5c,
	0x53, 0xc6, 0x17, 0x6d, 0xdf, 0x01, 0x00, 0x00, 0xff, 0xff, 0x9f, 0x36, 0x6b, 0x89, 0xff, 0x00,
	0x00, 0x00,
}
