// Code generated by protoc-gen-go. DO NOT EDIT.
// source: usercenter/t_memberunsignconfig.proto

package models

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "github.com/golang/protobuf/ptypes/timestamp"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type TMemberUnsignConfig struct {
	ActionScoreId        string   `protobuf:"bytes,1,opt,name=action_score_id,json=actionScoreId,proto3" json:"action_score_id,omitempty"`
	PtMemberScore        string   `protobuf:"bytes,2,opt,name=pt_member_score,json=ptMemberScore,proto3" json:"pt_member_score,omitempty"`
	QtMemberScore        string   `protobuf:"bytes,3,opt,name=qt_member_score,json=qtMemberScore,proto3" json:"qt_member_score,omitempty"`
	ByMemberScore        string   `protobuf:"bytes,4,opt,name=by_member_score,json=byMemberScore,proto3" json:"by_member_score,omitempty"`
	HjMemberScore        string   `protobuf:"bytes,5,opt,name=hj_member_score,json=hjMemberScore,proto3" json:"hj_member_score,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TMemberUnsignConfig) Reset()         { *m = TMemberUnsignConfig{} }
func (m *TMemberUnsignConfig) String() string { return proto.CompactTextString(m) }
func (*TMemberUnsignConfig) ProtoMessage()    {}
func (*TMemberUnsignConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_t_memberunsignconfig_7ba87d0bb97e6906, []int{0}
}
func (m *TMemberUnsignConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TMemberUnsignConfig.Unmarshal(m, b)
}
func (m *TMemberUnsignConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TMemberUnsignConfig.Marshal(b, m, deterministic)
}
func (dst *TMemberUnsignConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TMemberUnsignConfig.Merge(dst, src)
}
func (m *TMemberUnsignConfig) XXX_Size() int {
	return xxx_messageInfo_TMemberUnsignConfig.Size(m)
}
func (m *TMemberUnsignConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_TMemberUnsignConfig.DiscardUnknown(m)
}

var xxx_messageInfo_TMemberUnsignConfig proto.InternalMessageInfo

func (m *TMemberUnsignConfig) GetActionScoreId() string {
	if m != nil {
		return m.ActionScoreId
	}
	return ""
}

func (m *TMemberUnsignConfig) GetPtMemberScore() string {
	if m != nil {
		return m.PtMemberScore
	}
	return ""
}

func (m *TMemberUnsignConfig) GetQtMemberScore() string {
	if m != nil {
		return m.QtMemberScore
	}
	return ""
}

func (m *TMemberUnsignConfig) GetByMemberScore() string {
	if m != nil {
		return m.ByMemberScore
	}
	return ""
}

func (m *TMemberUnsignConfig) GetHjMemberScore() string {
	if m != nil {
		return m.HjMemberScore
	}
	return ""
}

func init() {
	proto.RegisterType((*TMemberUnsignConfig)(nil), "usercenter.TMemberUnsignConfig")
}

func init() {
	proto.RegisterFile("usercenter/t_memberunsignconfig.proto", fileDescriptor_t_memberunsignconfig_7ba87d0bb97e6906)
}

var fileDescriptor_t_memberunsignconfig_7ba87d0bb97e6906 = []byte{
	// 224 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0xcf, 0x3f, 0x4b, 0x04, 0x31,
	0x10, 0x05, 0x70, 0xd6, 0x3f, 0x87, 0x06, 0x44, 0x38, 0x9b, 0xc3, 0x4a, 0x04, 0xc5, 0xea, 0x52,
	0x58, 0xda, 0x69, 0x65, 0x61, 0xe3, 0x9f, 0xc6, 0x66, 0xd9, 0x64, 0xe7, 0xb2, 0x39, 0x2e, 0x99,
	0x6c, 0x32, 0x29, 0xf6, 0xc3, 0xfa, 0x5d, 0x64, 0x33, 0xc8, 0xba, 0xdb, 0x85, 0xc7, 0x8f, 0xf7,
	0x32, 0xe2, 0x2e, 0x27, 0x88, 0x1a, 0x3c, 0x41, 0x94, 0x54, 0x3b, 0x70, 0x0a, 0x62, 0xf6, 0xc9,
	0x1a, 0xaf, 0xd1, 0xef, 0xac, 0xd9, 0x86, 0x88, 0x84, 0x6b, 0x31, 0xb1, 0xeb, 0x27, 0x63, 0xa9,
	0xcb, 0x6a, 0xab, 0xd1, 0x49, 0x83, 0x87, 0xc6, 0x1b, 0x59, 0x90, 0xca, 0x3b, 0x19, 0x68, 0x08,
	0x90, 0x24, 0x59, 0x07, 0x89, 0x1a, 0x17, 0xa6, 0x17, 0x17, 0xdd, 0xfe, 0x54, 0xe2, 0xea, 0xf3,
	0xad, 0xcc, 0x7c, 0x95, 0x99, 0x97, 0x32, 0xb3, 0xbe, 0x17, 0x97, 0x8d, 0x26, 0x8b, 0xbe, 0x4e,
	0x1a, 0x23, 0xd4, 0xb6, 0xdd, 0x54, 0x37, 0xd5, 0xc3, 0xf9, 0xfb, 0x05, 0xc7, 0x1f, 0x63, 0xfa,
	0xda, 0x8e, 0x2e, 0xfc, 0xfd, 0x93, 0xe9, 0xe6, 0x88, 0x5d, 0x20, 0xae, 0x2d, 0x72, 0x74, 0xfd,
	0xc2, 0x1d, 0xb3, 0xeb, 0x97, 0x4e, 0x0d, 0x73, 0x77, 0xc2, 0x4e, 0x0d, 0x0b, 0xd7, 0xed, 0xe7,
	0xee, 0x94, 0x5d, 0xb7, 0xff, 0xe7, 0x9e, 0xcf, 0xbe, 0x57, 0x0e, 0x5b, 0x38, 0x24, 0xb5, 0x2a,
	0x07, 0x3f, 0xfe, 0x06, 0x00, 0x00, 0xff, 0xff, 0xa8, 0xc7, 0x07, 0xf9, 0x62, 0x01, 0x00, 0x00,
}
