// Code generated by protoc-gen-go. DO NOT EDIT.
// source: usercenter/t_rightspackageorder.proto

package models

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import timestamp "github.com/golang/protobuf/ptypes/timestamp"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type TRightsPackageOrder struct {
	Id                   string               `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Mobile               string               `protobuf:"bytes,2,opt,name=mobile,proto3" json:"mobile,omitempty"`
	OrderDate            *timestamp.Timestamp `protobuf:"bytes,3,opt,name=order_date,json=orderDate,proto3" json:"order_date,omitempty"`
	Type                 string               `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`
	OrderNum             string               `protobuf:"bytes,5,opt,name=order_num,json=orderNum,proto3" json:"order_num,omitempty"`
	TransactionId        string               `protobuf:"bytes,6,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	LockDate             *timestamp.Timestamp `protobuf:"bytes,7,opt,name=lock_date,json=lockDate,proto3" json:"lock_date,omitempty"`
	ConfirmDate          *timestamp.Timestamp `protobuf:"bytes,8,opt,name=confirm_date,json=confirmDate,proto3" json:"confirm_date,omitempty"`
	Status               string               `protobuf:"bytes,9,opt,name=status,proto3" json:"status,omitempty"`
	ExpireDate           *timestamp.Timestamp `protobuf:"bytes,10,opt,name=expire_date,json=expireDate,proto3" json:"expire_date,omitempty"`
	ExchangeNum          string               `protobuf:"bytes,11,opt,name=exchange_num,json=exchangeNum,proto3" json:"exchange_num,omitempty"`
	PartitionId          string               `protobuf:"bytes,12,opt,name=partition_id,json=partitionId,proto3" json:"partition_id,omitempty"`
	CreateDate           *timestamp.Timestamp `protobuf:"bytes,13,opt,name=create_date,json=createDate,proto3" json:"create_date,omitempty"`
	Msisdn               string               `protobuf:"bytes,14,opt,name=msisdn,proto3" json:"msisdn,omitempty"`
	Feemsisdn            string               `protobuf:"bytes,15,opt,name=feemsisdn,proto3" json:"feemsisdn,omitempty"`
	PayCode              string               `protobuf:"bytes,16,opt,name=pay_code,json=payCode,proto3" json:"pay_code,omitempty"`
	SubsSeq              string               `protobuf:"bytes,17,opt,name=subs_seq,json=subsSeq,proto3" json:"subs_seq,omitempty"`
	ChannelId            string               `protobuf:"bytes,18,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *TRightsPackageOrder) Reset()         { *m = TRightsPackageOrder{} }
func (m *TRightsPackageOrder) String() string { return proto.CompactTextString(m) }
func (*TRightsPackageOrder) ProtoMessage()    {}
func (*TRightsPackageOrder) Descriptor() ([]byte, []int) {
	return fileDescriptor_t_rightspackageorder_dbdef7dc9b134c57, []int{0}
}
func (m *TRightsPackageOrder) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TRightsPackageOrder.Unmarshal(m, b)
}
func (m *TRightsPackageOrder) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TRightsPackageOrder.Marshal(b, m, deterministic)
}
func (dst *TRightsPackageOrder) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TRightsPackageOrder.Merge(dst, src)
}
func (m *TRightsPackageOrder) XXX_Size() int {
	return xxx_messageInfo_TRightsPackageOrder.Size(m)
}
func (m *TRightsPackageOrder) XXX_DiscardUnknown() {
	xxx_messageInfo_TRightsPackageOrder.DiscardUnknown(m)
}

var xxx_messageInfo_TRightsPackageOrder proto.InternalMessageInfo

func (m *TRightsPackageOrder) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *TRightsPackageOrder) GetMobile() string {
	if m != nil {
		return m.Mobile
	}
	return ""
}

func (m *TRightsPackageOrder) GetOrderDate() *timestamp.Timestamp {
	if m != nil {
		return m.OrderDate
	}
	return nil
}

func (m *TRightsPackageOrder) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *TRightsPackageOrder) GetOrderNum() string {
	if m != nil {
		return m.OrderNum
	}
	return ""
}

func (m *TRightsPackageOrder) GetTransactionId() string {
	if m != nil {
		return m.TransactionId
	}
	return ""
}

func (m *TRightsPackageOrder) GetLockDate() *timestamp.Timestamp {
	if m != nil {
		return m.LockDate
	}
	return nil
}

func (m *TRightsPackageOrder) GetConfirmDate() *timestamp.Timestamp {
	if m != nil {
		return m.ConfirmDate
	}
	return nil
}

func (m *TRightsPackageOrder) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *TRightsPackageOrder) GetExpireDate() *timestamp.Timestamp {
	if m != nil {
		return m.ExpireDate
	}
	return nil
}

func (m *TRightsPackageOrder) GetExchangeNum() string {
	if m != nil {
		return m.ExchangeNum
	}
	return ""
}

func (m *TRightsPackageOrder) GetPartitionId() string {
	if m != nil {
		return m.PartitionId
	}
	return ""
}

func (m *TRightsPackageOrder) GetCreateDate() *timestamp.Timestamp {
	if m != nil {
		return m.CreateDate
	}
	return nil
}

func (m *TRightsPackageOrder) GetMsisdn() string {
	if m != nil {
		return m.Msisdn
	}
	return ""
}

func (m *TRightsPackageOrder) GetFeemsisdn() string {
	if m != nil {
		return m.Feemsisdn
	}
	return ""
}

func (m *TRightsPackageOrder) GetPayCode() string {
	if m != nil {
		return m.PayCode
	}
	return ""
}

func (m *TRightsPackageOrder) GetSubsSeq() string {
	if m != nil {
		return m.SubsSeq
	}
	return ""
}

func (m *TRightsPackageOrder) GetChannelId() string {
	if m != nil {
		return m.ChannelId
	}
	return ""
}

func init() {
	proto.RegisterType((*TRightsPackageOrder)(nil), "usercenter.TRightsPackageOrder")
}

func init() {
	proto.RegisterFile("usercenter/t_rightspackageorder.proto", fileDescriptor_t_rightspackageorder_dbdef7dc9b134c57)
}

var fileDescriptor_t_rightspackageorder_dbdef7dc9b134c57 = []byte{
	// 437 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x51, 0xc1, 0x6e, 0xd4, 0x30,
	0x10, 0xd5, 0x2e, 0x6d, 0x9a, 0x4c, 0xb6, 0x0b, 0x18, 0xa9, 0x32, 0x05, 0xa4, 0x16, 0xa9, 0x52,
	0x4f, 0x89, 0x04, 0x07, 0x84, 0x2a, 0x2e, 0xc0, 0x65, 0x2f, 0x80, 0x96, 0x9e, 0xb8, 0x44, 0x4e,
	0x3c, 0x9b, 0xb5, 0x9a, 0xc4, 0xa9, 0xed, 0x48, 0xbb, 0xdf, 0xc4, 0x4f, 0x22, 0x8f, 0x13, 0xb6,
	0xb7, 0xbd, 0x79, 0xde, 0x7b, 0xf3, 0xe6, 0xcd, 0x18, 0x6e, 0x06, 0x8b, 0xa6, 0xc2, 0xce, 0xa1,
	0xc9, 0x5d, 0x61, 0x54, 0xbd, 0x75, 0xb6, 0x17, 0xd5, 0x83, 0xa8, 0x51, 0x1b, 0x89, 0x26, 0xeb,
	0x8d, 0x76, 0x9a, 0xc1, 0x41, 0x76, 0x79, 0x57, 0x2b, 0xb7, 0x1d, 0xca, 0xac, 0xd2, 0x6d, 0x5e,
	0xeb, 0x46, 0x74, 0x75, 0x4e, 0xa2, 0x72, 0xd8, 0xe4, 0xbd, 0xdb, 0xf7, 0x68, 0x73, 0xa7, 0x5a,
	0xb4, 0x4e, 0xb4, 0xfd, 0xe1, 0x15, 0x8c, 0xde, 0xff, 0x3d, 0x85, 0x57, 0xf7, 0x6b, 0x1a, 0xf3,
	0x2b, 0x8c, 0xf9, 0xe9, 0xc7, 0xb0, 0x25, 0xcc, 0x95, 0xe4, 0xb3, 0xab, 0xd9, 0x6d, 0xb2, 0x9e,
	0x2b, 0xc9, 0x2e, 0x20, 0x6a, 0x75, 0xa9, 0x1a, 0xe4, 0x73, 0xc2, 0xc6, 0x8a, 0x7d, 0x06, 0xa0,
	0x5c, 0x85, 0x14, 0x0e, 0xf9, 0xb3, 0xab, 0xd9, 0x6d, 0xfa, 0xe1, 0x32, 0xab, 0xb5, 0xae, 0x1b,
	0xcc, 0xa6, 0x18, 0xd9, 0xfd, 0x34, 0x75, 0x9d, 0x90, 0xfa, 0xbb, 0x70, 0xc8, 0x18, 0x9c, 0xf8,
	0x74, 0xfc, 0x84, 0x0c, 0xe9, 0xcd, 0xde, 0x40, 0x10, 0x14, 0xdd, 0xd0, 0xf2, 0x53, 0x22, 0x62,
	0x02, 0x7e, 0x0c, 0x2d, 0xbb, 0x81, 0xa5, 0x33, 0xa2, 0xb3, 0xa2, 0x72, 0x4a, 0x77, 0x85, 0x92,
	0x3c, 0x22, 0xc5, 0xf9, 0x13, 0x74, 0x25, 0xd9, 0x27, 0x48, 0x1a, 0x5d, 0x3d, 0x84, 0x44, 0x67,
	0x47, 0x13, 0xc5, 0x5e, 0x4c, 0x81, 0xbe, 0xc0, 0xa2, 0xd2, 0xdd, 0x46, 0x99, 0x36, 0xf4, 0xc6,
	0x47, 0x7b, 0xd3, 0x51, 0x4f, 0xed, 0x17, 0x10, 0x59, 0x27, 0xdc, 0x60, 0x79, 0x12, 0x4e, 0x14,
	0x2a, 0x76, 0x07, 0x29, 0xee, 0x7a, 0x65, 0x30, 0xb8, 0xc2, 0x51, 0x57, 0x08, 0x72, 0x32, 0xbd,
	0x86, 0x05, 0xee, 0xaa, 0xad, 0xe8, 0x6a, 0xa4, 0x9b, 0xa4, 0x64, 0x9d, 0x4e, 0x98, 0x3f, 0xcb,
	0x35, 0x2c, 0x7a, 0x61, 0x9c, 0x9a, 0x8e, 0xb2, 0x08, 0x92, 0xff, 0xd8, 0x4a, 0xfa, 0x08, 0x95,
	0x41, 0xe1, 0xc6, 0x08, 0xe7, 0xc7, 0x23, 0x04, 0xf9, 0xb4, 0x57, 0x6b, 0x95, 0x95, 0x1d, 0x5f,
	0x8e, 0x5f, 0x4f, 0x15, 0x7b, 0x0b, 0xc9, 0x06, 0x71, 0xa4, 0x9e, 0x13, 0x75, 0x00, 0xd8, 0x6b,
	0x88, 0x7b, 0xb1, 0x2f, 0x2a, 0x2d, 0x91, 0xbf, 0x20, 0xf2, 0xac, 0x17, 0xfb, 0x6f, 0x5a, 0xa2,
	0xa7, 0xec, 0x50, 0xda, 0xc2, 0xe2, 0x23, 0x7f, 0x19, 0x28, 0x5f, 0xff, 0xc6, 0x47, 0xf6, 0x0e,
	0xc0, 0x2f, 0xd6, 0x61, 0xe3, 0x37, 0x61, 0xc1, 0x74, 0x44, 0x56, 0xf2, 0x6b, 0xfc, 0x27, 0x6a,
	0xb5, 0xc4, 0xc6, 0x96, 0x11, 0x85, 0xfe, 0xf8, 0x2f, 0x00, 0x00, 0xff, 0xff, 0x2d, 0x7d, 0x17,
	0xa2, 0x30, 0x03, 0x00, 0x00,
}
