// Code generated by protoc-gen-go. DO NOT EDIT.
// source: usercenter/t_screeningmodel.proto

package models

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import timestamp "github.com/golang/protobuf/ptypes/timestamp"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type TScreeningModel struct {
	Id                   string               `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string               `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	CreateDate           *timestamp.Timestamp `protobuf:"bytes,3,opt,name=create_date,json=createDate,proto3" json:"create_date,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *TScreeningModel) Reset()         { *m = TScreeningModel{} }
func (m *TScreeningModel) String() string { return proto.CompactTextString(m) }
func (*TScreeningModel) ProtoMessage()    {}
func (*TScreeningModel) Descriptor() ([]byte, []int) {
	return fileDescriptor_t_screeningmodel_b40aaffa4ec04a5b, []int{0}
}
func (m *TScreeningModel) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TScreeningModel.Unmarshal(m, b)
}
func (m *TScreeningModel) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TScreeningModel.Marshal(b, m, deterministic)
}
func (dst *TScreeningModel) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TScreeningModel.Merge(dst, src)
}
func (m *TScreeningModel) XXX_Size() int {
	return xxx_messageInfo_TScreeningModel.Size(m)
}
func (m *TScreeningModel) XXX_DiscardUnknown() {
	xxx_messageInfo_TScreeningModel.DiscardUnknown(m)
}

var xxx_messageInfo_TScreeningModel proto.InternalMessageInfo

func (m *TScreeningModel) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *TScreeningModel) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *TScreeningModel) GetCreateDate() *timestamp.Timestamp {
	if m != nil {
		return m.CreateDate
	}
	return nil
}

func init() {
	proto.RegisterType((*TScreeningModel)(nil), "usercenter.TScreeningModel")
}

func init() {
	proto.RegisterFile("usercenter/t_screeningmodel.proto", fileDescriptor_t_screeningmodel_b40aaffa4ec04a5b)
}

var fileDescriptor_t_screeningmodel_b40aaffa4ec04a5b = []byte{
	// 198 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x44, 0x8f, 0x3f, 0x6b, 0x85, 0x30,
	0x14, 0x47, 0xd1, 0x16, 0x69, 0x23, 0xb4, 0x90, 0x49, 0x9c, 0x6c, 0x27, 0xa7, 0x04, 0xda, 0xd1,
	0xad, 0x74, 0xed, 0x62, 0x9d, 0xba, 0x48, 0x4c, 0x6e, 0xf3, 0x02, 0xe6, 0x0f, 0xc9, 0x75, 0x78,
	0xdf, 0xfe, 0xf1, 0x22, 0xe2, 0x76, 0xb8, 0x1c, 0xee, 0xe1, 0x47, 0xde, 0xb6, 0x04, 0x51, 0x82,
	0x43, 0x88, 0x1c, 0xe7, 0x24, 0x23, 0x80, 0x33, 0x4e, 0x5b, 0xaf, 0x60, 0x65, 0x21, 0x7a, 0xf4,
	0x94, 0x9c, 0x4a, 0x3b, 0x68, 0x83, 0x97, 0x6d, 0x61, 0xd2, 0x5b, 0xae, 0xfd, 0x2a, 0x9c, 0xe6,
	0x59, 0x5a, 0xb6, 0x7f, 0x1e, 0xf0, 0x1a, 0x20, 0x71, 0x34, 0x16, 0x12, 0x0a, 0x1b, 0x4e, 0xda,
	0x1f, 0xbd, 0x47, 0xf2, 0x3a, 0xfd, 0x1e, 0x85, 0x9f, 0x7b, 0x81, 0xbe, 0x90, 0xd2, 0xa8, 0xa6,
	0xe8, 0x8a, 0xfe, 0x79, 0x2c, 0x8d, 0xa2, 0x94, 0x3c, 0x3a, 0x61, 0xa1, 0x29, 0xf3, 0x25, 0x33,
	0x1d, 0x48, 0x2d, 0x23, 0x08, 0x84, 0x59, 0x09, 0x84, 0xe6, 0xa1, 0x2b, 0xfa, 0xfa, 0xa3, 0x65,
	0xda, 0x7b, 0xbd, 0x02, 0x3b, 0xf2, 0x6c, 0x3a, 0x6a, 0x23, 0xd9, 0xf5, 0x6f, 0x81, 0xf0, 0xf5,
	0xf4, 0x57, 0xe5, 0x2d, 0x69, 0xa9, 0xb2, 0xf9, 0x79, 0x0b, 0x00, 0x00, 0xff, 0xff, 0x53, 0xcc,
	0x4b, 0x1d, 0xf2, 0x00, 0x00, 0x00,
}
