// Code generated by protoc-gen-go. DO NOT EDIT.
// source: usercenter/t_tesst01.proto

package models

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "github.com/golang/protobuf/ptypes/timestamp"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type TTesst01 struct {
	Msgtype              string   `protobuf:"bytes,1,opt,name=msgtype,proto3" json:"msgtype,omitempty"`
	Description          string   `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Content              string   `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	Status               string   `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TTesst01) Reset()         { *m = TTesst01{} }
func (m *TTesst01) String() string { return proto.CompactTextString(m) }
func (*TTesst01) ProtoMessage()    {}
func (*TTesst01) Descriptor() ([]byte, []int) {
	return fileDescriptor_t_tesst01_70a8f40611dee154, []int{0}
}
func (m *TTesst01) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TTesst01.Unmarshal(m, b)
}
func (m *TTesst01) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TTesst01.Marshal(b, m, deterministic)
}
func (dst *TTesst01) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TTesst01.Merge(dst, src)
}
func (m *TTesst01) XXX_Size() int {
	return xxx_messageInfo_TTesst01.Size(m)
}
func (m *TTesst01) XXX_DiscardUnknown() {
	xxx_messageInfo_TTesst01.DiscardUnknown(m)
}

var xxx_messageInfo_TTesst01 proto.InternalMessageInfo

func (m *TTesst01) GetMsgtype() string {
	if m != nil {
		return m.Msgtype
	}
	return ""
}

func (m *TTesst01) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *TTesst01) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *TTesst01) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func init() {
	proto.RegisterType((*TTesst01)(nil), "usercenter.TTesst01")
}

func init() {
	proto.RegisterFile("usercenter/t_tesst01.proto", fileDescriptor_t_tesst01_70a8f40611dee154)
}

var fileDescriptor_t_tesst01_70a8f40611dee154 = []byte{
	// 190 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x8e, 0x3d, 0x6b, 0xc3, 0x30,
	0x10, 0x86, 0x71, 0x5b, 0x5c, 0x57, 0xdd, 0x34, 0x14, 0xe1, 0xc9, 0x74, 0xea, 0x64, 0xb5, 0x74,
	0xcc, 0x96, 0x9f, 0x10, 0x3c, 0x65, 0x09, 0xb6, 0x7c, 0x51, 0x04, 0xd6, 0x07, 0xba, 0x13, 0x24,
	0xff, 0x3e, 0x58, 0x76, 0x70, 0xb6, 0x7b, 0xef, 0xb9, 0xe7, 0xe5, 0x58, 0x9d, 0x10, 0xa2, 0x02,
	0x47, 0x10, 0x25, 0x9d, 0x08, 0x10, 0xe9, 0xf7, 0xaf, 0x0d, 0xd1, 0x93, 0xe7, 0x6c, 0x63, 0xf5,
	0x4e, 0x1b, 0xba, 0xa4, 0xa1, 0x55, 0xde, 0x4a, 0xed, 0xa7, 0xde, 0x69, 0x99, 0x8f, 0x86, 0x74,
	0x96, 0x81, 0x6e, 0x01, 0x50, 0x92, 0xb1, 0x80, 0xd4, 0xdb, 0xb0, 0x4d, 0x4b, 0xd1, 0xf7, 0x95,
	0x55, 0x5d, 0xb7, 0x54, 0x73, 0xc1, 0xde, 0x2d, 0xea, 0xd9, 0x10, 0x45, 0x53, 0xfc, 0x7c, 0x1c,
	0x1e, 0x91, 0x37, 0xec, 0x73, 0x04, 0x54, 0xd1, 0x04, 0x32, 0xde, 0x89, 0x97, 0x4c, 0x9f, 0x57,
	0xb3, 0xab, 0xbc, 0x23, 0x70, 0x24, 0x5e, 0x17, 0x77, 0x8d, 0xfc, 0x8b, 0x95, 0x48, 0x3d, 0x25,
	0x14, 0x6f, 0x19, 0xac, 0x69, 0x5f, 0x1d, 0x4b, 0xeb, 0x47, 0x98, 0x70, 0x28, 0xf3, 0x2b, 0xff,
	0xf7, 0x00, 0x00, 0x00, 0xff, 0xff, 0xd4, 0xe0, 0xb1, 0x5c, 0xf1, 0x00, 0x00, 0x00,
}
