// Code generated by protoc-gen-go. DO NOT EDIT.
// source: usercenter/t_tqborderinfohist.proto

package models

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import timestamp "github.com/golang/protobuf/ptypes/timestamp"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type TTqbOrderinfoHist struct {
	Histid               string               `protobuf:"bytes,1,opt,name=histid,proto3" json:"histid,omitempty"`
	Orderid              string               `protobuf:"bytes,2,opt,name=orderid,proto3" json:"orderid,omitempty"`
	Checkid              string               `protobuf:"bytes,3,opt,name=checkid,proto3" json:"checkid,omitempty"`
	Tradeid              string               `protobuf:"bytes,4,opt,name=tradeid,proto3" json:"tradeid,omitempty"`
	Subsid               string               `protobuf:"bytes,5,opt,name=subsid,proto3" json:"subsid,omitempty"`
	Chargesubsid         string               `protobuf:"bytes,6,opt,name=chargesubsid,proto3" json:"chargesubsid,omitempty"`
	Ordertype            string               `protobuf:"bytes,7,opt,name=ordertype,proto3" json:"ordertype,omitempty"`
	Orderpayment         string               `protobuf:"bytes,8,opt,name=orderpayment,proto3" json:"orderpayment,omitempty"`
	Appid                string               `protobuf:"bytes,9,opt,name=appid,proto3" json:"appid,omitempty"`
	Paycode              string               `protobuf:"bytes,10,opt,name=paycode,proto3" json:"paycode,omitempty"`
	Programid            string               `protobuf:"bytes,11,opt,name=programid,proto3" json:"programid,omitempty"`
	Orderstatus          string               `protobuf:"bytes,12,opt,name=orderstatus,proto3" json:"orderstatus,omitempty"`
	Startdate            *timestamp.Timestamp `protobuf:"bytes,13,opt,name=startdate,proto3" json:"startdate,omitempty"`
	Lastchgdate          *timestamp.Timestamp `protobuf:"bytes,14,opt,name=lastchgdate,proto3" json:"lastchgdate,omitempty"`
	Subnplace            string               `protobuf:"bytes,15,opt,name=subnplace,proto3" json:"subnplace,omitempty"`
	Lastsendmcoinmonth   *timestamp.Timestamp `protobuf:"bytes,16,opt,name=lastsendmcoinmonth,proto3" json:"lastsendmcoinmonth,omitempty"`
	Price                string               `protobuf:"bytes,17,opt,name=price,proto3" json:"price,omitempty"`
	Subsreq              string               `protobuf:"bytes,18,opt,name=subsreq,proto3" json:"subsreq,omitempty"`
	Md5Sign              string               `protobuf:"bytes,19,opt,name=md5sign,proto3" json:"md5sign,omitempty"`
	Exdata               string               `protobuf:"bytes,20,opt,name=exdata,proto3" json:"exdata,omitempty"`
	Returnstatus         string               `protobuf:"bytes,21,opt,name=returnstatus,proto3" json:"returnstatus,omitempty"`
	Provinceid           string               `protobuf:"bytes,22,opt,name=provinceid,proto3" json:"provinceid,omitempty"`
	Channelid            string               `protobuf:"bytes,23,opt,name=channelid,proto3" json:"channelid,omitempty"`
	Inserttime           *timestamp.Timestamp `protobuf:"bytes,24,opt,name=inserttime,proto3" json:"inserttime,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *TTqbOrderinfoHist) Reset()         { *m = TTqbOrderinfoHist{} }
func (m *TTqbOrderinfoHist) String() string { return proto.CompactTextString(m) }
func (*TTqbOrderinfoHist) ProtoMessage()    {}
func (*TTqbOrderinfoHist) Descriptor() ([]byte, []int) {
	return fileDescriptor_t_tqborderinfohist_26f49f6bf3e01b7e, []int{0}
}
func (m *TTqbOrderinfoHist) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TTqbOrderinfoHist.Unmarshal(m, b)
}
func (m *TTqbOrderinfoHist) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TTqbOrderinfoHist.Marshal(b, m, deterministic)
}
func (dst *TTqbOrderinfoHist) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TTqbOrderinfoHist.Merge(dst, src)
}
func (m *TTqbOrderinfoHist) XXX_Size() int {
	return xxx_messageInfo_TTqbOrderinfoHist.Size(m)
}
func (m *TTqbOrderinfoHist) XXX_DiscardUnknown() {
	xxx_messageInfo_TTqbOrderinfoHist.DiscardUnknown(m)
}

var xxx_messageInfo_TTqbOrderinfoHist proto.InternalMessageInfo

func (m *TTqbOrderinfoHist) GetHistid() string {
	if m != nil {
		return m.Histid
	}
	return ""
}

func (m *TTqbOrderinfoHist) GetOrderid() string {
	if m != nil {
		return m.Orderid
	}
	return ""
}

func (m *TTqbOrderinfoHist) GetCheckid() string {
	if m != nil {
		return m.Checkid
	}
	return ""
}

func (m *TTqbOrderinfoHist) GetTradeid() string {
	if m != nil {
		return m.Tradeid
	}
	return ""
}

func (m *TTqbOrderinfoHist) GetSubsid() string {
	if m != nil {
		return m.Subsid
	}
	return ""
}

func (m *TTqbOrderinfoHist) GetChargesubsid() string {
	if m != nil {
		return m.Chargesubsid
	}
	return ""
}

func (m *TTqbOrderinfoHist) GetOrdertype() string {
	if m != nil {
		return m.Ordertype
	}
	return ""
}

func (m *TTqbOrderinfoHist) GetOrderpayment() string {
	if m != nil {
		return m.Orderpayment
	}
	return ""
}

func (m *TTqbOrderinfoHist) GetAppid() string {
	if m != nil {
		return m.Appid
	}
	return ""
}

func (m *TTqbOrderinfoHist) GetPaycode() string {
	if m != nil {
		return m.Paycode
	}
	return ""
}

func (m *TTqbOrderinfoHist) GetProgramid() string {
	if m != nil {
		return m.Programid
	}
	return ""
}

func (m *TTqbOrderinfoHist) GetOrderstatus() string {
	if m != nil {
		return m.Orderstatus
	}
	return ""
}

func (m *TTqbOrderinfoHist) GetStartdate() *timestamp.Timestamp {
	if m != nil {
		return m.Startdate
	}
	return nil
}

func (m *TTqbOrderinfoHist) GetLastchgdate() *timestamp.Timestamp {
	if m != nil {
		return m.Lastchgdate
	}
	return nil
}

func (m *TTqbOrderinfoHist) GetSubnplace() string {
	if m != nil {
		return m.Subnplace
	}
	return ""
}

func (m *TTqbOrderinfoHist) GetLastsendmcoinmonth() *timestamp.Timestamp {
	if m != nil {
		return m.Lastsendmcoinmonth
	}
	return nil
}

func (m *TTqbOrderinfoHist) GetPrice() string {
	if m != nil {
		return m.Price
	}
	return ""
}

func (m *TTqbOrderinfoHist) GetSubsreq() string {
	if m != nil {
		return m.Subsreq
	}
	return ""
}

func (m *TTqbOrderinfoHist) GetMd5Sign() string {
	if m != nil {
		return m.Md5Sign
	}
	return ""
}

func (m *TTqbOrderinfoHist) GetExdata() string {
	if m != nil {
		return m.Exdata
	}
	return ""
}

func (m *TTqbOrderinfoHist) GetReturnstatus() string {
	if m != nil {
		return m.Returnstatus
	}
	return ""
}

func (m *TTqbOrderinfoHist) GetProvinceid() string {
	if m != nil {
		return m.Provinceid
	}
	return ""
}

func (m *TTqbOrderinfoHist) GetChannelid() string {
	if m != nil {
		return m.Channelid
	}
	return ""
}

func (m *TTqbOrderinfoHist) GetInserttime() *timestamp.Timestamp {
	if m != nil {
		return m.Inserttime
	}
	return nil
}

func init() {
	proto.RegisterType((*TTqbOrderinfoHist)(nil), "usercenter.TTqbOrderinfoHist")
}

func init() {
	proto.RegisterFile("usercenter/t_tqborderinfohist.proto", fileDescriptor_t_tqborderinfohist_26f49f6bf3e01b7e)
}

var fileDescriptor_t_tqborderinfohist_26f49f6bf3e01b7e = []byte{
	// 482 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x53, 0xcf, 0x8b, 0x13, 0x31,
	0x14, 0xa6, 0xea, 0xce, 0x6e, 0xd3, 0xf5, 0xc7, 0xc6, 0x75, 0x7d, 0x2c, 0x22, 0x65, 0xbd, 0xec,
	0x69, 0x06, 0x14, 0x41, 0xd4, 0x93, 0x27, 0xf1, 0x22, 0x2c, 0x3d, 0x79, 0x91, 0x4c, 0xf2, 0x3a,
	0x13, 0x9c, 0x49, 0xd2, 0xe4, 0x8d, 0xd8, 0x3f, 0xd1, 0xff, 0x4a, 0x92, 0x4c, 0xdb, 0x11, 0x16,
	0x7a, 0xeb, 0xf7, 0x23, 0xf9, 0x5e, 0xbf, 0x97, 0x61, 0x6f, 0x86, 0x80, 0x5e, 0xa2, 0x21, 0xf4,
	0x15, 0xfd, 0xa4, 0x4d, 0x6d, 0xbd, 0x42, 0xaf, 0xcd, 0xda, 0xb6, 0x3a, 0x50, 0xe9, 0xbc, 0x25,
	0xcb, 0xd9, 0xc1, 0x74, 0xfd, 0xa9, 0xd1, 0xd4, 0x0e, 0x75, 0x29, 0x6d, 0x5f, 0x35, 0xb6, 0x13,
	0xa6, 0xa9, 0x92, 0xa9, 0x1e, 0xd6, 0x95, 0xa3, 0xad, 0xc3, 0x50, 0x91, 0xee, 0x31, 0x90, 0xe8,
	0xdd, 0xe1, 0x57, 0xbe, 0xe8, 0xe6, 0x6f, 0xc1, 0x2e, 0x56, 0xab, 0x4d, 0xfd, 0x7d, 0x17, 0xf2,
	0x55, 0x07, 0xe2, 0x57, 0xac, 0x88, 0x61, 0x5a, 0xc1, 0x6c, 0x39, 0xbb, 0x9d, 0xdf, 0x8d, 0x88,
	0x03, 0x3b, 0xcd, 0xd3, 0x28, 0x78, 0x90, 0x84, 0x1d, 0x8c, 0x8a, 0x6c, 0x51, 0xfe, 0xd2, 0x0a,
	0x1e, 0x66, 0x65, 0x84, 0x51, 0x21, 0x2f, 0x14, 0x6a, 0x05, 0x8f, 0xb2, 0x32, 0xc2, 0x98, 0x12,
	0x86, 0x3a, 0x68, 0x05, 0x27, 0x39, 0x25, 0x23, 0x7e, 0xc3, 0xce, 0x65, 0x2b, 0x7c, 0x83, 0xa3,
	0x5a, 0x24, 0xf5, 0x3f, 0x8e, 0xbf, 0x62, 0xf3, 0x14, 0x1d, 0xff, 0x1f, 0x9c, 0x26, 0xc3, 0x81,
	0x88, 0x37, 0x24, 0xe0, 0xc4, 0xb6, 0x47, 0x43, 0x70, 0x96, 0x6f, 0x98, 0x72, 0xfc, 0x92, 0x9d,
	0x08, 0xe7, 0xb4, 0x82, 0x79, 0x12, 0x33, 0x88, 0xd3, 0x3a, 0xb1, 0x95, 0x56, 0x21, 0xb0, 0x3c,
	0xed, 0x08, 0x63, 0xa2, 0xf3, 0xb6, 0xf1, 0xa2, 0xd7, 0x0a, 0x16, 0x39, 0x71, 0x4f, 0xf0, 0x25,
	0x5b, 0xa4, 0xdb, 0x03, 0x09, 0x1a, 0x02, 0x9c, 0x27, 0x7d, 0x4a, 0xf1, 0x0f, 0x6c, 0x1e, 0x48,
	0x78, 0x52, 0x82, 0x10, 0x1e, 0x2f, 0x67, 0xb7, 0x8b, 0xb7, 0xd7, 0x65, 0x63, 0x6d, 0xd3, 0x61,
	0xb9, 0xdb, 0x57, 0xb9, 0xda, 0xad, 0xe7, 0xee, 0x60, 0xe6, 0x9f, 0xd9, 0xa2, 0x13, 0x81, 0x64,
	0xdb, 0xa4, 0xb3, 0x4f, 0x8e, 0x9e, 0x9d, 0xda, 0xe3, 0xdc, 0x61, 0xa8, 0x8d, 0xeb, 0x84, 0x44,
	0x78, 0x9a, 0xe7, 0xde, 0x13, 0xfc, 0x1b, 0xe3, 0xd1, 0x1c, 0xd0, 0xa8, 0x5e, 0x5a, 0x6d, 0x7a,
	0x6b, 0xa8, 0x85, 0x67, 0x47, 0x23, 0xee, 0x39, 0x15, 0x1b, 0x75, 0x5e, 0x4b, 0x84, 0x8b, 0xdc,
	0x68, 0x02, 0xb1, 0xd1, 0xb8, 0x33, 0x8f, 0x1b, 0xe0, 0xb9, 0xd1, 0x11, 0x46, 0xa5, 0x57, 0xef,
	0x83, 0x6e, 0x0c, 0x3c, 0xcf, 0xca, 0x08, 0xe3, 0xcb, 0xc0, 0x3f, 0x4a, 0x90, 0x80, 0xcb, 0xfc,
	0x32, 0x32, 0x8a, 0x7b, 0xf5, 0x48, 0x83, 0x37, 0x63, 0xcd, 0x2f, 0xf2, 0x5e, 0xa7, 0x1c, 0x7f,
	0xcd, 0x98, 0xf3, 0xf6, 0xb7, 0x36, 0x32, 0x3e, 0xb9, 0xab, 0xe4, 0x98, 0x30, 0xb1, 0x0f, 0xd9,
	0x0a, 0x63, 0xb0, 0xd3, 0x0a, 0x5e, 0xe6, 0x3e, 0xf6, 0x04, 0xff, 0xc8, 0x98, 0x36, 0x01, 0x3d,
	0xc5, 0x0f, 0x05, 0xe0, 0x68, 0x0f, 0x13, 0xf7, 0x97, 0xb3, 0x1f, 0x45, 0x6f, 0x15, 0x76, 0xa1,
	0x2e, 0x92, 0xf3, 0xdd, 0xbf, 0x00, 0x00, 0x00, 0xff, 0xff, 0x75, 0x69, 0x0a, 0xcd, 0xcc, 0x03,
	0x00, 0x00,
}
