// Code generated by protoc-gen-go. DO NOT EDIT.
// source: usercenter/t_tqborderinfo.proto

package models

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import timestamp "github.com/golang/protobuf/ptypes/timestamp"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type TTqbOrderinfo struct {
	Orderid              string               `protobuf:"bytes,1,opt,name=orderid,proto3" json:"orderid,omitempty"`
	Checkid              string               `protobuf:"bytes,2,opt,name=checkid,proto3" json:"checkid,omitempty"`
	Tradeid              string               `protobuf:"bytes,3,opt,name=tradeid,proto3" json:"tradeid,omitempty"`
	Subsid               string               `protobuf:"bytes,4,opt,name=subsid,proto3" json:"subsid,omitempty"`
	Chargesubsid         string               `protobuf:"bytes,5,opt,name=chargesubsid,proto3" json:"chargesubsid,omitempty"`
	Ordertype            string               `protobuf:"bytes,6,opt,name=ordertype,proto3" json:"ordertype,omitempty"`
	Orderpayment         string               `protobuf:"bytes,7,opt,name=orderpayment,proto3" json:"orderpayment,omitempty"`
	Appid                string               `protobuf:"bytes,8,opt,name=appid,proto3" json:"appid,omitempty"`
	Paycode              string               `protobuf:"bytes,9,opt,name=paycode,proto3" json:"paycode,omitempty"`
	Programid            string               `protobuf:"bytes,10,opt,name=programid,proto3" json:"programid,omitempty"`
	Orderstatus          string               `protobuf:"bytes,11,opt,name=orderstatus,proto3" json:"orderstatus,omitempty"`
	Startdate            *timestamp.Timestamp `protobuf:"bytes,12,opt,name=startdate,proto3" json:"startdate,omitempty"`
	Lastchgdate          *timestamp.Timestamp `protobuf:"bytes,13,opt,name=lastchgdate,proto3" json:"lastchgdate,omitempty"`
	Subnplace            string               `protobuf:"bytes,14,opt,name=subnplace,proto3" json:"subnplace,omitempty"`
	Lastsendmcoinmonth   *timestamp.Timestamp `protobuf:"bytes,15,opt,name=lastsendmcoinmonth,proto3" json:"lastsendmcoinmonth,omitempty"`
	Price                string               `protobuf:"bytes,16,opt,name=price,proto3" json:"price,omitempty"`
	Subsreq              string               `protobuf:"bytes,17,opt,name=subsreq,proto3" json:"subsreq,omitempty"`
	Md5Sign              string               `protobuf:"bytes,18,opt,name=md5sign,proto3" json:"md5sign,omitempty"`
	Exdata               string               `protobuf:"bytes,19,opt,name=exdata,proto3" json:"exdata,omitempty"`
	Returnstatus         string               `protobuf:"bytes,20,opt,name=returnstatus,proto3" json:"returnstatus,omitempty"`
	Channelid            string               `protobuf:"bytes,21,opt,name=channelid,proto3" json:"channelid,omitempty"`
	Provinceid           string               `protobuf:"bytes,22,opt,name=provinceid,proto3" json:"provinceid,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *TTqbOrderinfo) Reset()         { *m = TTqbOrderinfo{} }
func (m *TTqbOrderinfo) String() string { return proto.CompactTextString(m) }
func (*TTqbOrderinfo) ProtoMessage()    {}
func (*TTqbOrderinfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_t_tqborderinfo_c20098ae0189dd13, []int{0}
}
func (m *TTqbOrderinfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TTqbOrderinfo.Unmarshal(m, b)
}
func (m *TTqbOrderinfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TTqbOrderinfo.Marshal(b, m, deterministic)
}
func (dst *TTqbOrderinfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TTqbOrderinfo.Merge(dst, src)
}
func (m *TTqbOrderinfo) XXX_Size() int {
	return xxx_messageInfo_TTqbOrderinfo.Size(m)
}
func (m *TTqbOrderinfo) XXX_DiscardUnknown() {
	xxx_messageInfo_TTqbOrderinfo.DiscardUnknown(m)
}

var xxx_messageInfo_TTqbOrderinfo proto.InternalMessageInfo

func (m *TTqbOrderinfo) GetOrderid() string {
	if m != nil {
		return m.Orderid
	}
	return ""
}

func (m *TTqbOrderinfo) GetCheckid() string {
	if m != nil {
		return m.Checkid
	}
	return ""
}

func (m *TTqbOrderinfo) GetTradeid() string {
	if m != nil {
		return m.Tradeid
	}
	return ""
}

func (m *TTqbOrderinfo) GetSubsid() string {
	if m != nil {
		return m.Subsid
	}
	return ""
}

func (m *TTqbOrderinfo) GetChargesubsid() string {
	if m != nil {
		return m.Chargesubsid
	}
	return ""
}

func (m *TTqbOrderinfo) GetOrdertype() string {
	if m != nil {
		return m.Ordertype
	}
	return ""
}

func (m *TTqbOrderinfo) GetOrderpayment() string {
	if m != nil {
		return m.Orderpayment
	}
	return ""
}

func (m *TTqbOrderinfo) GetAppid() string {
	if m != nil {
		return m.Appid
	}
	return ""
}

func (m *TTqbOrderinfo) GetPaycode() string {
	if m != nil {
		return m.Paycode
	}
	return ""
}

func (m *TTqbOrderinfo) GetProgramid() string {
	if m != nil {
		return m.Programid
	}
	return ""
}

func (m *TTqbOrderinfo) GetOrderstatus() string {
	if m != nil {
		return m.Orderstatus
	}
	return ""
}

func (m *TTqbOrderinfo) GetStartdate() *timestamp.Timestamp {
	if m != nil {
		return m.Startdate
	}
	return nil
}

func (m *TTqbOrderinfo) GetLastchgdate() *timestamp.Timestamp {
	if m != nil {
		return m.Lastchgdate
	}
	return nil
}

func (m *TTqbOrderinfo) GetSubnplace() string {
	if m != nil {
		return m.Subnplace
	}
	return ""
}

func (m *TTqbOrderinfo) GetLastsendmcoinmonth() *timestamp.Timestamp {
	if m != nil {
		return m.Lastsendmcoinmonth
	}
	return nil
}

func (m *TTqbOrderinfo) GetPrice() string {
	if m != nil {
		return m.Price
	}
	return ""
}

func (m *TTqbOrderinfo) GetSubsreq() string {
	if m != nil {
		return m.Subsreq
	}
	return ""
}

func (m *TTqbOrderinfo) GetMd5Sign() string {
	if m != nil {
		return m.Md5Sign
	}
	return ""
}

func (m *TTqbOrderinfo) GetExdata() string {
	if m != nil {
		return m.Exdata
	}
	return ""
}

func (m *TTqbOrderinfo) GetReturnstatus() string {
	if m != nil {
		return m.Returnstatus
	}
	return ""
}

func (m *TTqbOrderinfo) GetChannelid() string {
	if m != nil {
		return m.Channelid
	}
	return ""
}

func (m *TTqbOrderinfo) GetProvinceid() string {
	if m != nil {
		return m.Provinceid
	}
	return ""
}

func init() {
	proto.RegisterType((*TTqbOrderinfo)(nil), "usercenter.TTqbOrderinfo")
}

func init() {
	proto.RegisterFile("usercenter/t_tqborderinfo.proto", fileDescriptor_t_tqborderinfo_c20098ae0189dd13)
}

var fileDescriptor_t_tqborderinfo_c20098ae0189dd13 = []byte{
	// 451 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x52, 0x4d, 0x8b, 0x14, 0x31,
	0x10, 0x65, 0xd4, 0x99, 0xdd, 0xc9, 0xec, 0xfa, 0x11, 0xd7, 0xa5, 0x58, 0x44, 0x87, 0x3d, 0xed,
	0xa9, 0x1b, 0x14, 0x41, 0xd0, 0x93, 0x47, 0x2f, 0xc2, 0x32, 0x27, 0x2f, 0x92, 0x4e, 0x6a, 0xbb,
	0x83, 0x9d, 0x8f, 0x49, 0xaa, 0xc5, 0xf9, 0xd9, 0xfe, 0x03, 0x49, 0xd2, 0x33, 0xd3, 0x82, 0x30,
	0xb7, 0xbc, 0xf7, 0x2a, 0xf5, 0xea, 0x8b, 0xbd, 0x1d, 0x22, 0x06, 0x89, 0x96, 0x30, 0xd4, 0xf4,
	0x83, 0xb6, 0x8d, 0x0b, 0x0a, 0x83, 0xb6, 0x0f, 0xae, 0xf2, 0xc1, 0x91, 0xe3, 0xec, 0x18, 0x70,
	0xf3, 0xa9, 0xd5, 0xd4, 0x0d, 0x4d, 0x25, 0x9d, 0xa9, 0x5b, 0xd7, 0x0b, 0xdb, 0xd6, 0x39, 0xa8,
	0x19, 0x1e, 0x6a, 0x4f, 0x3b, 0x8f, 0xb1, 0x26, 0x6d, 0x30, 0x92, 0x30, 0xfe, 0xf8, 0x2a, 0x89,
	0x6e, 0xff, 0xcc, 0xd9, 0xe5, 0x66, 0xb3, 0x6d, 0xbe, 0xed, 0x0d, 0x38, 0xb0, 0xb3, 0xe2, 0xa6,
	0x60, 0xb6, 0x9e, 0xdd, 0x2d, 0xef, 0xf7, 0x30, 0x29, 0xb2, 0x43, 0xf9, 0x53, 0x2b, 0x78, 0x54,
	0x94, 0x11, 0x26, 0x85, 0x82, 0x50, 0xa8, 0x15, 0x3c, 0x2e, 0xca, 0x08, 0xf9, 0x35, 0x5b, 0xc4,
	0xa1, 0x89, 0x5a, 0xc1, 0x93, 0x2c, 0x8c, 0x88, 0xdf, 0xb2, 0x0b, 0xd9, 0x89, 0xd0, 0xe2, 0xa8,
	0xce, 0xb3, 0xfa, 0x0f, 0xc7, 0x5f, 0xb3, 0x65, 0xb6, 0x4e, 0x3d, 0xc0, 0x22, 0x07, 0x1c, 0x89,
	0x94, 0x21, 0x03, 0x2f, 0x76, 0x06, 0x2d, 0xc1, 0x59, 0xc9, 0x30, 0xe5, 0xf8, 0x15, 0x9b, 0x0b,
	0xef, 0xb5, 0x82, 0xf3, 0x2c, 0x16, 0x90, 0xaa, 0xf5, 0x62, 0x27, 0x9d, 0x42, 0x58, 0x96, 0x6a,
	0x47, 0x98, 0x1c, 0x7d, 0x70, 0x6d, 0x10, 0x46, 0x2b, 0x60, 0xc5, 0xf1, 0x40, 0xf0, 0x35, 0x5b,
	0xe5, 0xec, 0x91, 0x04, 0x0d, 0x11, 0x56, 0x59, 0x9f, 0x52, 0xfc, 0x23, 0x5b, 0x46, 0x12, 0x81,
	0x94, 0x20, 0x84, 0x8b, 0xf5, 0xec, 0x6e, 0xf5, 0xee, 0xa6, 0x6a, 0x9d, 0x6b, 0x7b, 0xac, 0xf6,
	0x3b, 0xa9, 0x36, 0xfb, 0x15, 0xdc, 0x1f, 0x83, 0xf9, 0x67, 0xb6, 0xea, 0x45, 0x24, 0xd9, 0xb5,
	0xf9, 0xef, 0xe5, 0xc9, 0xbf, 0xd3, 0xf0, 0x54, 0x77, 0x1c, 0x1a, 0xeb, 0x7b, 0x21, 0x11, 0x9e,
	0x96, 0xba, 0x0f, 0x04, 0xff, 0xca, 0x78, 0x0a, 0x8e, 0x68, 0x95, 0x91, 0x4e, 0x5b, 0xe3, 0x2c,
	0x75, 0xf0, 0xec, 0xa4, 0xc5, 0x7f, 0x7e, 0xa5, 0x89, 0xfa, 0xa0, 0x25, 0xc2, 0xf3, 0x32, 0xd1,
	0x0c, 0xd2, 0x44, 0xd3, 0xce, 0x02, 0x6e, 0xe1, 0x45, 0x99, 0xe8, 0x08, 0x93, 0x62, 0xd4, 0x87,
	0xa8, 0x5b, 0x0b, 0xbc, 0x28, 0x23, 0x4c, 0x97, 0x81, 0xbf, 0x95, 0x20, 0x01, 0x2f, 0xcb, 0x65,
	0x14, 0x94, 0xf6, 0x1a, 0x90, 0x86, 0x60, 0xc7, 0x31, 0x5f, 0x95, 0xbd, 0x4e, 0xb9, 0xd4, 0xaf,
	0xec, 0x84, 0xb5, 0xd8, 0x6b, 0x05, 0xaf, 0x4a, 0xbf, 0x07, 0x82, 0xbf, 0x61, 0xcc, 0x07, 0xf7,
	0x4b, 0x5b, 0x99, 0x0e, 0xf2, 0x3a, 0xcb, 0x13, 0xe6, 0xcb, 0xf9, 0xf7, 0x85, 0x71, 0x0a, 0xfb,
	0xd8, 0x2c, 0x72, 0xd7, 0xef, 0xff, 0x06, 0x00, 0x00, 0xff, 0xff, 0x76, 0x6a, 0xa6, 0xc0, 0x70,
	0x03, 0x00, 0x00,
}
