// Code generated by protoc-gen-go. DO NOT EDIT.
// source: usercenter/t_userportraittemp.proto

package models

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import timestamp "github.com/golang/protobuf/ptypes/timestamp"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type TUserPortraitTemp struct {
	Mobile               string               `protobuf:"bytes,1,opt,name=mobile,proto3" json:"mobile,omitempty"`
	LableId1             string               `protobuf:"bytes,2,opt,name=lable_id1,json=lableId1,proto3" json:"lable_id1,omitempty"`
	LableName1           string               `protobuf:"bytes,3,opt,name=lable_name1,json=lableName1,proto3" json:"lable_name1,omitempty"`
	LableId2             string               `protobuf:"bytes,4,opt,name=lable_id2,json=lableId2,proto3" json:"lable_id2,omitempty"`
	LableName2           string               `protobuf:"bytes,5,opt,name=lable_name2,json=lableName2,proto3" json:"lable_name2,omitempty"`
	LableId3             string               `protobuf:"bytes,6,opt,name=lable_id3,json=lableId3,proto3" json:"lable_id3,omitempty"`
	LableName3           string               `protobuf:"bytes,7,opt,name=lable_name3,json=lableName3,proto3" json:"lable_name3,omitempty"`
	LableId4             string               `protobuf:"bytes,8,opt,name=lable_id4,json=lableId4,proto3" json:"lable_id4,omitempty"`
	LableName4           string               `protobuf:"bytes,9,opt,name=lable_name4,json=lableName4,proto3" json:"lable_name4,omitempty"`
	RegisterDate         *timestamp.Timestamp `protobuf:"bytes,10,opt,name=register_date,json=registerDate,proto3" json:"register_date,omitempty"`
	CreateDate           *timestamp.Timestamp `protobuf:"bytes,11,opt,name=create_date,json=createDate,proto3" json:"create_date,omitempty"`
	PartitionId          string               `protobuf:"bytes,12,opt,name=partition_id,json=partitionId,proto3" json:"partition_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *TUserPortraitTemp) Reset()         { *m = TUserPortraitTemp{} }
func (m *TUserPortraitTemp) String() string { return proto.CompactTextString(m) }
func (*TUserPortraitTemp) ProtoMessage()    {}
func (*TUserPortraitTemp) Descriptor() ([]byte, []int) {
	return fileDescriptor_t_userportraittemp_a2bcf3a2d9396739, []int{0}
}
func (m *TUserPortraitTemp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TUserPortraitTemp.Unmarshal(m, b)
}
func (m *TUserPortraitTemp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TUserPortraitTemp.Marshal(b, m, deterministic)
}
func (dst *TUserPortraitTemp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TUserPortraitTemp.Merge(dst, src)
}
func (m *TUserPortraitTemp) XXX_Size() int {
	return xxx_messageInfo_TUserPortraitTemp.Size(m)
}
func (m *TUserPortraitTemp) XXX_DiscardUnknown() {
	xxx_messageInfo_TUserPortraitTemp.DiscardUnknown(m)
}

var xxx_messageInfo_TUserPortraitTemp proto.InternalMessageInfo

func (m *TUserPortraitTemp) GetMobile() string {
	if m != nil {
		return m.Mobile
	}
	return ""
}

func (m *TUserPortraitTemp) GetLableId1() string {
	if m != nil {
		return m.LableId1
	}
	return ""
}

func (m *TUserPortraitTemp) GetLableName1() string {
	if m != nil {
		return m.LableName1
	}
	return ""
}

func (m *TUserPortraitTemp) GetLableId2() string {
	if m != nil {
		return m.LableId2
	}
	return ""
}

func (m *TUserPortraitTemp) GetLableName2() string {
	if m != nil {
		return m.LableName2
	}
	return ""
}

func (m *TUserPortraitTemp) GetLableId3() string {
	if m != nil {
		return m.LableId3
	}
	return ""
}

func (m *TUserPortraitTemp) GetLableName3() string {
	if m != nil {
		return m.LableName3
	}
	return ""
}

func (m *TUserPortraitTemp) GetLableId4() string {
	if m != nil {
		return m.LableId4
	}
	return ""
}

func (m *TUserPortraitTemp) GetLableName4() string {
	if m != nil {
		return m.LableName4
	}
	return ""
}

func (m *TUserPortraitTemp) GetRegisterDate() *timestamp.Timestamp {
	if m != nil {
		return m.RegisterDate
	}
	return nil
}

func (m *TUserPortraitTemp) GetCreateDate() *timestamp.Timestamp {
	if m != nil {
		return m.CreateDate
	}
	return nil
}

func (m *TUserPortraitTemp) GetPartitionId() string {
	if m != nil {
		return m.PartitionId
	}
	return ""
}

func init() {
	proto.RegisterType((*TUserPortraitTemp)(nil), "usercenter.TUserPortraitTemp")
}

func init() {
	proto.RegisterFile("usercenter/t_userportraittemp.proto", fileDescriptor_t_userportraittemp_a2bcf3a2d9396739)
}

var fileDescriptor_t_userportraittemp_a2bcf3a2d9396739 = []byte{
	// 317 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0xd0, 0xb1, 0x4e, 0xc3, 0x30,
	0x10, 0x06, 0x60, 0x95, 0x42, 0x68, 0x2f, 0x65, 0x20, 0x03, 0xb2, 0xca, 0x40, 0x81, 0xa5, 0x53,
	0xa2, 0x26, 0xd9, 0x3a, 0x20, 0x21, 0x96, 0x2e, 0x08, 0x55, 0x65, 0x61, 0x89, 0x9c, 0xe6, 0x08,
	0x96, 0xe2, 0xd8, 0xb2, 0xaf, 0x03, 0xef, 0xc7, 0x83, 0xa1, 0x3a, 0x2d, 0xad, 0xbb, 0xb0, 0xe5,
	0xfe, 0xbb, 0xef, 0x62, 0x1d, 0x3c, 0x6e, 0x2c, 0x9a, 0x35, 0xb6, 0x84, 0x26, 0xa1, 0x62, 0x5b,
	0x68, 0x65, 0xc8, 0x70, 0x41, 0x84, 0x52, 0xc7, 0xda, 0x28, 0x52, 0x11, 0x1c, 0x86, 0xc6, 0xf3,
	0x5a, 0xd0, 0xd7, 0xa6, 0x8c, 0xd7, 0x4a, 0x26, 0xb5, 0x6a, 0x78, 0x5b, 0x27, 0x6e, 0xa8, 0xdc,
	0x7c, 0x26, 0x9a, 0xbe, 0x35, 0xda, 0x84, 0x84, 0x44, 0x4b, 0x5c, 0xea, 0xc3, 0x57, 0xb7, 0xe8,
	0xe1, 0xa7, 0x0f, 0xd7, 0xab, 0x77, 0x8b, 0xe6, 0x6d, 0xf7, 0x93, 0x15, 0x4a, 0x1d, 0xdd, 0x40,
	0x20, 0x55, 0x29, 0x1a, 0x64, 0xbd, 0x49, 0x6f, 0x3a, 0x5c, 0xee, 0xaa, 0xe8, 0x16, 0x86, 0x0d,
	0x2f, 0x1b, 0x2c, 0x44, 0x35, 0x63, 0x67, 0xae, 0x35, 0x70, 0xc1, 0xa2, 0x9a, 0x45, 0x77, 0x10,
	0x76, 0xcd, 0x96, 0x4b, 0x9c, 0xb1, 0xbe, 0x6b, 0x83, 0x8b, 0x5e, 0xb7, 0xc9, 0xb1, 0x4e, 0xd9,
	0xb9, 0xa7, 0x53, 0x5f, 0xa7, 0xec, 0xe2, 0x44, 0xa7, 0xc7, 0x3a, 0x63, 0x81, 0xa7, 0x33, 0x5f,
	0x67, 0xec, 0xf2, 0x44, 0x67, 0xc7, 0x3a, 0x67, 0x03, 0x4f, 0xe7, 0xbe, 0xce, 0xd9, 0xf0, 0x44,
	0xe7, 0xd1, 0x13, 0x5c, 0x19, 0xac, 0x85, 0x25, 0x34, 0x45, 0xc5, 0x09, 0x19, 0x4c, 0x7a, 0xd3,
	0x30, 0x1d, 0xc7, 0xb5, 0x52, 0x75, 0x83, 0xf1, 0xfe, 0xde, 0xf1, 0x6a, 0x7f, 0xde, 0xe5, 0x68,
	0x0f, 0x5e, 0x38, 0x61, 0x34, 0x87, 0x70, 0x6d, 0x90, 0x13, 0x76, 0x3c, 0xfc, 0x97, 0x43, 0x37,
	0xee, 0xf0, 0x3d, 0x8c, 0x34, 0x37, 0x24, 0x48, 0xa8, 0xb6, 0x10, 0x15, 0x1b, 0xb9, 0xf7, 0x85,
	0x7f, 0xd9, 0xa2, 0x7a, 0x1e, 0x7c, 0x04, 0x52, 0x55, 0xd8, 0xd8, 0x32, 0x70, 0xcb, 0xb2, 0xdf,
	0x00, 0x00, 0x00, 0xff, 0xff, 0x0a, 0x22, 0x38, 0xa8, 0x47, 0x02, 0x00, 0x00,
}
