language: go
go:
- 1.8.3
- 1.9rc2
notifications:
  slack:
    secure: mm6qufDprHZPxD2ftZQoaSHYy8WMCwdAItn7RLX1a2bi8FfQsdRTwxUz2ZnB0MFOutjSaVxpVif4jRjc7knYaRQ0ddBG4BNA+GWVAT8vHTwE1JuTUc99WPsOsMBFYGFh8V9lbjevgRBZ6weWorP5m8UwhXeSsisILDshDWu8X3agTS3kiLPF4G0AWyfYHCk2aYaHkeL8BgzMCHOdVpCDBvxbCh5huytXSLq2Vrjmkgw5oDcQjMzLmirFAYFF0fXdPAhA0cCEFLgOzZsH5FiJh/MYwMOatxh8aiUsELAaQAarIlkg0ZROePhNRsMRP2xXhyrA/NlZVIqGM4jALfYwfILYU0mHTkK8BJpB4Zja4uZWoD8by06yswoqVR4cWKFU7GgsOJGeExIn564oPWc7k8Cf7u0oPBvGEinhl74Lh2KOxN/haSQS9Q/vJPg5LsjaWfEEcEEYBe4/yC+mvxdd3yDVBL8KsUZkC9On1quMDfT7sQj25I08Vh78DdR0g+Cip/qxNLPzl34gx7DVpCa4QJY2rWTJOXNx8EGssD+QDwajXGXYiar5jnPPWXPB7Va7wqq9eDfeetZfvEk3qPXKQtYfAmUGLkomdFsDOGLZ58o1MASOs9MDRNKJ9/E1MUH7QlItYUCOCodTyd1sGpGypBR25Eh9EaR9Ey6pVjpV+RY=
