// Code generated by protoc-gen-go. DO NOT EDIT.
// source: example.proto

package go_micro_srv_dbservice

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Preference struct {
	User                 int32    `protobuf:"varint,1,opt,name=user,proto3" json:"user,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Value                string   `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Preference) Reset()         { *m = Preference{} }
func (m *Preference) String() string { return proto.CompactTextString(m) }
func (*Preference) ProtoMessage()    {}
func (*Preference) Descriptor() ([]byte, []int) {
	return fileDescriptor_example_2c5e2019002a829e, []int{0}
}
func (m *Preference) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Preference.Unmarshal(m, b)
}
func (m *Preference) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Preference.Marshal(b, m, deterministic)
}
func (dst *Preference) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Preference.Merge(dst, src)
}
func (m *Preference) XXX_Size() int {
	return xxx_messageInfo_Preference.Size(m)
}
func (m *Preference) XXX_DiscardUnknown() {
	xxx_messageInfo_Preference.DiscardUnknown(m)
}

var xxx_messageInfo_Preference proto.InternalMessageInfo

func (m *Preference) GetUser() int32 {
	if m != nil {
		return m.User
	}
	return 0
}

func (m *Preference) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Preference) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type PreferenceRequest struct {
	User                 int32    `protobuf:"varint,1,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PreferenceRequest) Reset()         { *m = PreferenceRequest{} }
func (m *PreferenceRequest) String() string { return proto.CompactTextString(m) }
func (*PreferenceRequest) ProtoMessage()    {}
func (*PreferenceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_example_2c5e2019002a829e, []int{1}
}
func (m *PreferenceRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PreferenceRequest.Unmarshal(m, b)
}
func (m *PreferenceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PreferenceRequest.Marshal(b, m, deterministic)
}
func (dst *PreferenceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PreferenceRequest.Merge(dst, src)
}
func (m *PreferenceRequest) XXX_Size() int {
	return xxx_messageInfo_PreferenceRequest.Size(m)
}
func (m *PreferenceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PreferenceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PreferenceRequest proto.InternalMessageInfo

func (m *PreferenceRequest) GetUser() int32 {
	if m != nil {
		return m.User
	}
	return 0
}

type PreferenceResponse struct {
	ResultCode           int32       `protobuf:"varint,1,opt,name=resultCode,proto3" json:"resultCode,omitempty"`
	Prefer               *Preference `protobuf:"bytes,2,opt,name=prefer,proto3" json:"prefer,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *PreferenceResponse) Reset()         { *m = PreferenceResponse{} }
func (m *PreferenceResponse) String() string { return proto.CompactTextString(m) }
func (*PreferenceResponse) ProtoMessage()    {}
func (*PreferenceResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_example_2c5e2019002a829e, []int{2}
}
func (m *PreferenceResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PreferenceResponse.Unmarshal(m, b)
}
func (m *PreferenceResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PreferenceResponse.Marshal(b, m, deterministic)
}
func (dst *PreferenceResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PreferenceResponse.Merge(dst, src)
}
func (m *PreferenceResponse) XXX_Size() int {
	return xxx_messageInfo_PreferenceResponse.Size(m)
}
func (m *PreferenceResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PreferenceResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PreferenceResponse proto.InternalMessageInfo

func (m *PreferenceResponse) GetResultCode() int32 {
	if m != nil {
		return m.ResultCode
	}
	return 0
}

func (m *PreferenceResponse) GetPrefer() *Preference {
	if m != nil {
		return m.Prefer
	}
	return nil
}

type PreferencesListRequest struct {
	Index                int32    `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	Limit                int32    `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PreferencesListRequest) Reset()         { *m = PreferencesListRequest{} }
func (m *PreferencesListRequest) String() string { return proto.CompactTextString(m) }
func (*PreferencesListRequest) ProtoMessage()    {}
func (*PreferencesListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_example_2c5e2019002a829e, []int{3}
}
func (m *PreferencesListRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PreferencesListRequest.Unmarshal(m, b)
}
func (m *PreferencesListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PreferencesListRequest.Marshal(b, m, deterministic)
}
func (dst *PreferencesListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PreferencesListRequest.Merge(dst, src)
}
func (m *PreferencesListRequest) XXX_Size() int {
	return xxx_messageInfo_PreferencesListRequest.Size(m)
}
func (m *PreferencesListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PreferencesListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PreferencesListRequest proto.InternalMessageInfo

func (m *PreferencesListRequest) GetIndex() int32 {
	if m != nil {
		return m.Index
	}
	return 0
}

func (m *PreferencesListRequest) GetLimit() int32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

type PreferencesListResponse struct {
	ResultCode           int32         `protobuf:"varint,1,opt,name=resultCode,proto3" json:"resultCode,omitempty"`
	Prefers              []*Preference `protobuf:"bytes,2,rep,name=prefers,proto3" json:"prefers,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *PreferencesListResponse) Reset()         { *m = PreferencesListResponse{} }
func (m *PreferencesListResponse) String() string { return proto.CompactTextString(m) }
func (*PreferencesListResponse) ProtoMessage()    {}
func (*PreferencesListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_example_2c5e2019002a829e, []int{4}
}
func (m *PreferencesListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PreferencesListResponse.Unmarshal(m, b)
}
func (m *PreferencesListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PreferencesListResponse.Marshal(b, m, deterministic)
}
func (dst *PreferencesListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PreferencesListResponse.Merge(dst, src)
}
func (m *PreferencesListResponse) XXX_Size() int {
	return xxx_messageInfo_PreferencesListResponse.Size(m)
}
func (m *PreferencesListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PreferencesListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PreferencesListResponse proto.InternalMessageInfo

func (m *PreferencesListResponse) GetResultCode() int32 {
	if m != nil {
		return m.ResultCode
	}
	return 0
}

func (m *PreferencesListResponse) GetPrefers() []*Preference {
	if m != nil {
		return m.Prefers
	}
	return nil
}

func init() {
	proto.RegisterType((*Preference)(nil), "go.micro.srv.dbservice.Preference")
	proto.RegisterType((*PreferenceRequest)(nil), "go.micro.srv.dbservice.PreferenceRequest")
	proto.RegisterType((*PreferenceResponse)(nil), "go.micro.srv.dbservice.PreferenceResponse")
	proto.RegisterType((*PreferencesListRequest)(nil), "go.micro.srv.dbservice.PreferencesListRequest")
	proto.RegisterType((*PreferencesListResponse)(nil), "go.micro.srv.dbservice.PreferencesListResponse")
}

func init() { proto.RegisterFile("example.proto", fileDescriptor_example_2c5e2019002a829e) }

var fileDescriptor_example_2c5e2019002a829e = []byte{
	// 296 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x52, 0xcf, 0x4a, 0xfb, 0x40,
	0x10, 0xfe, 0xa5, 0xfd, 0xa5, 0xe2, 0x94, 0x1e, 0x1c, 0x4a, 0x0d, 0x3d, 0x48, 0xd8, 0x8b, 0xd5,
	0xc3, 0x0a, 0xf5, 0x26, 0xde, 0x14, 0x04, 0xf1, 0x20, 0x79, 0x83, 0x34, 0x19, 0x75, 0x21, 0xc9,
	0xc6, 0xdd, 0x4d, 0xda, 0xc7, 0xf6, 0x11, 0xa4, 0xbb, 0x09, 0x5d, 0xb1, 0x60, 0x6e, 0x33, 0x1f,
	0xdf, 0x7c, 0x7f, 0x92, 0x85, 0x19, 0xed, 0xd2, 0xb2, 0x2e, 0x88, 0xd7, 0x4a, 0x1a, 0x89, 0x8b,
	0x77, 0xc9, 0x4b, 0x91, 0x29, 0xc9, 0xb5, 0x6a, 0x79, 0xbe, 0xd1, 0xa4, 0x5a, 0x91, 0x11, 0x7b,
	0x06, 0x78, 0x55, 0xf4, 0x46, 0x8a, 0xaa, 0x8c, 0x10, 0xe1, 0x7f, 0xa3, 0x49, 0x45, 0x41, 0x1c,
	0xac, 0xc2, 0xc4, 0xce, 0x7b, 0xac, 0x4a, 0x4b, 0x8a, 0x46, 0x71, 0xb0, 0x3a, 0x4d, 0xec, 0x8c,
	0x73, 0x08, 0xdb, 0xb4, 0x68, 0x28, 0x1a, 0x5b, 0xd0, 0x2d, 0xec, 0x12, 0xce, 0x0e, 0x5a, 0x09,
	0x7d, 0x36, 0xa4, 0xcd, 0x31, 0x49, 0x56, 0x03, 0xfa, 0x44, 0x5d, 0xcb, 0x4a, 0x13, 0x5e, 0x00,
	0x28, 0xd2, 0x4d, 0x61, 0x1e, 0x64, 0x4e, 0x1d, 0xdf, 0x43, 0xf0, 0x0e, 0x26, 0xb5, 0xbd, 0xb2,
	0x51, 0xa6, 0x6b, 0xc6, 0x8f, 0x77, 0xe2, 0x9e, 0x76, 0x77, 0xc1, 0x1e, 0x61, 0x71, 0x40, 0xf5,
	0x8b, 0xd0, 0xa6, 0xcf, 0x37, 0x87, 0x50, 0x54, 0x39, 0xed, 0x3a, 0x43, 0xb7, 0xec, 0xd1, 0x42,
	0x94, 0xc2, 0x58, 0xab, 0x30, 0x71, 0x0b, 0xdb, 0xc2, 0xf9, 0x2f, 0x95, 0x81, 0xe1, 0xef, 0xe1,
	0xc4, 0x45, 0xd1, 0xd1, 0x28, 0x1e, 0x0f, 0x4c, 0xdf, 0x9f, 0xac, 0xbf, 0x02, 0x98, 0x7a, 0xce,
	0xf8, 0x01, 0xb3, 0x27, 0x32, 0xde, 0x8f, 0xbb, 0x1a, 0xa0, 0xe6, 0x0a, 0x2f, 0xaf, 0x87, 0x50,
	0x5d, 0x2b, 0xf6, 0x0f, 0xb7, 0x80, 0x3f, 0x9c, 0x6c, 0x6b, 0xe4, 0x7f, 0x6b, 0xf8, 0x1f, 0x79,
	0x79, 0x33, 0x98, 0xdf, 0x1b, 0x6f, 0x26, 0xf6, 0xdd, 0xde, 0x7e, 0x07, 0x00, 0x00, 0xff, 0xff,
	0x4c, 0xd9, 0xad, 0x84, 0xc8, 0x02, 0x00, 0x00,
}
