package main

import (
	"github.com/kennyzhu/go-os/dbservice/handler"
	//"github.com/kennyzhu/go-os/dbservice/subscriber"
	"github.com/micro/go-log"
	"github.com/micro/go-micro"

	example "github.com/kennyzhu/go-os/dbservice/proto/example"
)

//generated by: micro new --type srv --alias dbservice github.com/kennyzhu/go-os/
func main() {
	// New Service
	service := micro.NewService(
		micro.Name("go.micro.srv.dbservice"),
		micro.Version("1"),
	)

	// Initialise service
	service.Init()

	// Register Handler
	//each goroutine..
	example.RegisterExampleHandler(service.Server(), new(handler.Example))

	// Register Struct as Subscriber
	//micro.RegisterSubscriber("go.micro.srv.template", service.Server(), new(subscriber.Example))
	//micro.RegisterSubscriber("go.micro.srv.template", service.Server(), subscriber.Handler)

	// Run service
	if err := service.Run(); err != nil {
		log.Fatal(err)
	}
}
